src/interaction/interactionhandler.cpp
src/scene/scenegraphnode.cpp

I've built on Mac & Windows (VS2014) with these changes. Please review & pull to feature/osirisrex if looks good.

Made changes to accomodate Mac clang compiler

---

apps/Launcher/CMakeLists.txt
data/scene/earth/earth.mod
modules/base/CMakeLists.txt
modules/base/basemodule.cpp
modules/base/rendering/renderableplanet.cpp
modules/base/rendering/renderabletrail.cpp
modules/base/rendering/renderabletrailorbit.cpp
modules/base/rendering/renderabletrailtrajectory.cpp
modules/base/rotation/spicerotation.cpp
modules/base/translation/keplertranslation.cpp
modules/base/translation/keplertranslation.h
modules/base/translation/spicetranslation.cpp
modules/base/translation/tletranslation.cpp
modules/base/translation/tletranslation.h
modules/onscreengui/src/guipropertycomponent.cpp
src/scene/translation.cpp

A few other things have slipped into the PR as well, but well..

Support for Kepler and TLE Translations

---

apps/OpenSpace/main.cpp

Removed two extra headers.
Tested on all platforms.

Remove extra <thread> headers.

---

apps/Launcher/main.cpp
apps/Launcher/mainwindow.cpp

Changed "Cancel" button to "Exit"

Launcher checkbox colors are green (not so bright) or grey (not red)

---

src/mission/missionmanager.cpp

You can use the method for the condition since you have implemented it.

Using the implemented method for the condition.

---

include/openspace/rendering/renderengine.h
include/openspace/scene/scene.h
include/openspace/util/screenlog.h
src/rendering/renderengine.cpp
src/scene/scene.cpp
src/util/screenlog.cpp

Updates to #307:
Scene, Renderer, ScreenLog
closes #305 & closes #306

Missing Destructors: Issue #307

---

openspace.cfg

Add a performance warning (113186) ignore entry for OpenGL Debugger

---

ext/json/json.hpp

Figured I'd make a PR so I don't break other stuff with this.

Update json library to latest version

---

modules/base/rendering/renderabletrailorbit.cpp
modules/base/rendering/renderabletrailorbit.h

- Base orbit update on actual previous values instead of time jump concept
- Fix OpenGL invalid value bug caused by negative buffer size

Bug fix for orbits

---

apps/Launcher/mainwindow.cpp
src/engine/openspaceengine.cpp

Replace ${SGCT} token with ${CONFIG} in Launcher and OpenSpaceEngine.

---

modules/globebrowsing/tile/asynctiledataprovider.cpp
modules/globebrowsing/tile/tileprovider/defaulttileprovider.cpp
modules/globebrowsing/tile/tileprovider/texttileprovider.cpp

Include globebrowsing module to avoid linking errors

---

data/scene/default.scene
data/scene/osirisrex.scene
data/scene/satellites.scene

default, osirisrex, & satellites
closes #365

set openspace.navigation.resetCameraDirection()

---

support/joss/paper.md

Fixing up YAML affiliations

---

data/web/scenelicense/main.hbs
data/web/scenelicense/scenelicense.hbs
data/web/scenelicense/script.js
include/openspace/engine/configurationmanager.h
include/openspace/scene/scene.h
include/openspace/scene/scenelicense.h
include/openspace/scene/scenelicensewriter.h
include/openspace/scene/sceneloader.h
openspace.cfg
src/CMakeLists.txt
src/documentation/documentationgenerator.cpp
src/engine/configurationmanager.cpp
src/engine/configurationmanager_doc.inl
src/engine/openspaceengine.cpp
src/interaction/keybindingmanager.cpp
src/scene/scene.cpp
src/scene/scenelicense.cpp
src/scene/scenelicensewriter.cpp
src/scene/sceneloader.cpp

Add documentation generator to SceneLicense

Add SceneLicense information to the Scene

---

apps/OpenSpace/main.cpp
src/engine/openspaceengine.cpp

Do not let exception leak out of OpenSpaceEngine::create method
Add double dash to long name commandline arguments

Update Ghoul repository (closes #483)

---

modules/globebrowsing/tile/rawtiledatareader/gdalrawtiledatareader.cpp
modules/globebrowsing/tile/rawtiledatareader/gdalwrapper.cpp

Remove duplicate opening of GDAL datasets on failure (closes #478)

Add global timeout of 3 seconds to GDAL request

---

include/openspace/engine/openspaceengine.h
include/openspace/interaction/navigationhandler.h
include/openspace/scene/asset.h
modules/globebrowsing/globebrowsingmodule_lua.inl
modules/sync/syncmodule.cpp
modules/sync/tasks/syncassettask.cpp
modules/sync/torrentclient.cpp
modules/sync/torrentclient.h
src/engine/moduleengine.cpp
src/engine/moduleengine_lua.inl
src/engine/openspaceengine_lua.inl
src/engine/wrapper/windowwrapper.cpp
src/interaction/keybindingmanager_lua.inl
src/interaction/navigationhandler_lua.inl
src/mission/missionmanager_lua.inl
src/network/parallelconnection_lua.inl
src/rendering/dashboard.cpp
src/rendering/dashboard_lua.inl
src/rendering/renderengine_lua.inl
src/scene/asset.cpp
src/scene/assetloader.cpp
src/scene/assetmanager.cpp
src/scene/scene_lua.inl
src/scripting/scriptengine.cpp
src/scripting/scriptengine_lua.inl
src/scripting/scriptscheduler_lua.inl
src/util/spicemanager_lua.inl
src/util/time_lua.inl

- Clean the lua stack in the end of several lua c functions, to fix crash occuring when tearing down the lua state.
- Make sure listeners are notified when torrents changes state.

Fix asset bugs

---

modules/base/shaders/model_fs.glsl
modules/base/shaders/model_vs.glsl

Added missing support for G-Buffer from RenderableModel.

Added support to G-Buffer.

---

modules/globebrowsing/scripts/layer_support.lua

@alexanderbock: I had some issues with .info files after the Name -> Identifier change.
Is this the proper way to solve it? This would also require changing the info files themselves. Not sure if there is a central repo for those, where that should be changed in that case?
(I tried this locally and it works) :)

Change Name to Identifier in globe browsing helper code

---

modules/server/include/timetopic.h
modules/server/src/topics/timetopic.cpp

Fixes https://github.com/OpenSpace/OpenSpace/issues/611

Make it possible to unsubscribe to the time

---

include/openspace/interaction/navigationhandler.h
include/openspace/interaction/orbitalnavigator.h
modules/imgui/src/guispacetimecomponent.cpp
src/interaction/navigationhandler.cpp
src/interaction/orbitalnavigator.cpp

Implement https://github.com/OpenSpace/OpenSpace/issues/698

Add shortcut to change focus interpolation time

---

data/assets/examples/debugcoordinateaxes.asset
data/assets/util/debug_helper.asset
include/openspace/engine/openspaceengine.h
modules/base/CMakeLists.txt
modules/base/basemodule.cpp
modules/base/rendering/renderablecartesianaxes.cpp
modules/base/rendering/renderablecartesianaxes.h
modules/base/shaders/axes_fs.glsl
modules/base/shaders/axes_vs.glsl
src/engine/openspaceengine.cpp
src/scene/sceneinitializer.cpp

- Add coordinate axes renderable
- Add debug helper asset for coordinate systems + grids
- Fix bug with dynamic loading of assets
- Add example asset

Add debug helper for coordinate systems

---

src/scene/assetloader.cpp

Add asset.filePath to asset api

---

modules/touch/src/touchinteraction.cpp
modules/touch/touchmodule.cpp

Tested touch interaction with and without the webbrowser module.

Changed touch module to allow build with/without webbrowser module enabled

---

src/interaction/sessionrecording.cpp

fix for session recording to support macro variables

---

data/assets/scene/solarsystem/planets/earth/satellites/debris/debris_asat.asset

Attempt to fix case-sensitive branch name problem

Merging Emil's space debris branch into the official thesis/2019/spaceDebris branch

---

modules/webbrowser/include/browserclient.h
modules/webbrowser/src/browserclient.cpp

Works on Mac. Yet to be tested on Windows.

Disable context menu to fix #828

---

data/assets/scene/digitaluniverse/dwarfs.asset
data/assets/scene/digitaluniverse/globularclusters.asset
data/assets/scene/digitaluniverse/h2regions.asset
data/assets/scene/digitaluniverse/milkyway.asset
data/assets/scene/digitaluniverse/obassociations.asset
data/assets/scene/digitaluniverse/planetarynebulae.asset
data/assets/scene/digitaluniverse/pulsars.asset
data/assets/scene/digitaluniverse/quasars.asset
data/assets/scene/digitaluniverse/supernovaremnants.asset
data/assets/util/webgui.asset
include/openspace/interaction/sessionrecording.h
include/openspace/rendering/renderable.h
modules/server/include/topics/sessionrecordingtopic.h
modules/server/src/topics/getpropertytopic.cpp
modules/server/src/topics/sessionrecordingtopic.cpp
src/interaction/sessionrecording.cpp
src/rendering/renderable.cpp

I know we don't want to be adding extra properties, but I didn't know another way to expose the RenderableType to the gui. Open to any other suggestions.

exposed renderable type to gui, fixed path for milkyway items

---

data/assets/scene/solarsystem/sun/glare.asset
modules/base/rendering/renderableplaneimagelocal.cpp
modules/base/rendering/renderabletrail.cpp
modules/base/rendering/renderabletrailorbit.cpp

Fixed depth sorting for Sun's glare.

Fixed depth sorting for Sun's glare.

---

include/openspace/rendering/framebufferrenderer.h
modules/atmosphere/shaders/atmosphere_deferred_fs.glsl
src/rendering/framebufferrenderer.cpp

Enabled global fade-out back again.

Fixed global fade-out.

---

data/assets/scene/digitaluniverse/grids.asset

Added Oort sphere grid.

---

data/assets/scene/solarsystem/missions/pioneer/pioneer10.asset
data/assets/scene/solarsystem/missions/pioneer/pioneer11.asset

Sync file: https://drive.google.com/file/d/1Zxk6mGz2izvTs9XcdDwh3pu3GifyK6QT/view?usp=sharing

updated pioneer model to v2

---

config/openvr_htcVive.xml
config/openvr_oculusRiftCv1.xml
config/single.xml
config/single_fisheye.xml
config/single_gui.xml
config/single_two_win.xml

fix for https://github.com/OpenSpace/OpenSpace/issues/894

updated number of samples for configs to make gui work on macs

---

data/assets/apollo_sites.scene
data/assets/scene/solarsystem/missions/apollo/apollo11.asset

apollo_11_spice : https://drive.google.com/file/d/1DuvZRdfpr1Z_XA9CXdoWK93pOch4N0Il/view?usp=sharing
apollo_11_models: https://drive.google.com/file/d/1AjnikWEwzoEOoKCoxPPu1ddKs4XV_xwW/view?usp=sharing

added apollo 11 CSM orbits and mock lem decent

---

.gitmodules
apps/OpenSpace-MinVR/CMakeLists.txt
apps/OpenSpace-MinVR/main.cpp

adjusted CMakeLists.txt to use renamed openspace-core module
converted main.cpp mouse button callback to have modifiers as 3rd argument
added ghoul initialization for ${BIN} etc.
There is no issues, but I can create one if it's desirable to have it :-)

three minVR updates

---

data/assets/scene/milkyway/milkyway/volume.asset
modules/galaxy/shaders/points_vs.glsl

This removes a hard coded value from the shader and makes it possible to focus on the center of the milky way

Use a StaticTranslation to position the Milky Way

---

modules/webbrowser/src/webbrowserapp.cpp
modules/webbrowser/webbrowsermodule.cpp

This improves performance especially when using the CEF web gui by using certain command line switches and by reducing the time intervall to pump the cef message loop about once every 10 milliseconds in the regular update loop.

Improvements in Performance due to adopted usage of CEF Message Loop

---

modules/digitaluniverse/shaders/billboard_fs.glsl
modules/digitaluniverse/shaders/billboard_gs.glsl
modules/space/shaders/star_ge.glsl

Fixed star rendering cuts on cubemap borders.

Issue/981 - Star Rendering Cuts

---

data/assets/scene/solarsystem/planets/earth/satellites/misc/iss.asset

Adding the satellite trail for ISS

Adding iss asset as a renderablesatellite

---

modules/imgui/imguimodule.cpp
modules/imgui/imguimodule.h
modules/imgui/include/gui.h
modules/imgui/src/gui.cpp
modules/touch/include/touchinteraction.h
modules/touch/src/touchinteraction.cpp

Also removed imgui-handling code in touchinteraction
Same PR as https://github.com/OpenSpace/OpenSpace/pull/1119 but for the SPVL project branch

[SPVL]Made imgui handle touch input as the webgui does

---

modules/imgui/imguimodule.cpp
modules/imgui/imguimodule.h
modules/imgui/include/gui.h
modules/imgui/src/gui.cpp
modules/touch/include/touchinteraction.h
modules/touch/src/touchinteraction.cpp

Also removed imgui-handling code in touchinteraction
Should be non-intrusive for those cases where we don't have touch input enabled. 
Closes https://github.com/OpenSpace/OpenSpace/issues/1039

Made imgui handle touch input as the webgui does

---

data/assets/scene/solarsystem/missions/voyager/voyager1.asset
data/assets/scene/solarsystem/missions/voyager/voyager2.asset
modules/space/spacemodule.cpp
openspace.cfg

disabled spice exceptions by default; updated space module to read spiceexpection value;

aded time range to voyager rotations; 

---

modules/base/rendering/renderablesphere.cpp

Enabled back the disable/enable of fade in/out effects.

Fixed issue.

---

modules/base/rendering/renderablemodel.cpp
modules/base/rendering/renderablemodel.h
modules/base/shaders/model_vs.glsl

Corrections for the issue of ISS's normals when rendering in fisheye mode.

Fixed ISS' normals transformation.

---

modules/atmosphere/rendering/atmospheredeferredcaster.cpp
modules/atmosphere/rendering/atmospheredeferredcaster.h
modules/atmosphere/shaders/atmosphere_deferred_fs.glsl
modules/globebrowsing/shaders/renderer_fs.glsl
modules/globebrowsing/src/renderableglobe.cpp

Eclipses scaling correctly with the bodies' sizes.

Added scaling properties to eclipses.

---

modules/exoplanets/rendering/renderableorbitdisc.h
modules/exoplanets/tasks/exoplanetscsvtobintask.cpp

@jccosta, please make sure it works on Linux and then feel free to merge :)

Fix for compile errors for Linux in exoplanets module

---

data/assets/scene/digitaluniverse/stars.asset
modules/space/shaders/star_fs.glsl
src/rendering/framebufferrenderer.cpp

We now initialize the position buffer in g-Buffer with a different value than zero.
This correction fixes the issue when the MilkyWay sphere is not present, and the atmospheres are enabled.

Added initial position (far away) in the g-Buffer position.

---

modules/globebrowsing/src/renderableglobe.cpp
modules/globebrowsing/src/ringscomponent.cpp
modules/globebrowsing/src/shadowcomponent.cpp
modules/globebrowsing/src/shadowcomponent.h

Fixes for issue 1432: Error and warnings being displayed when one gets close to Saturn.

Fixed issue 1432: globebrowsing and shadow mapping.

---

data/assets/scene/digitaluniverse/deepsky.asset
modules/digitaluniverse/rendering/renderableplanescloud.cpp

Fixed units for the Deep Sky Objects and increased the maximum scale range to facilitate the localization and viewing of these objects.

Fixed Deep Sky Objects basic unit and increased maximum scale range.

---

modules/iswa/rendering/iswacygnet.cpp
tests/AssetLoaderTest/assetfunctionsexist.asset
tests/test_documentation.cpp
tests/test_luaconversions.cpp

With this branch, all tests pass on windows as well

Fixes for getting all unit tests passing on linux

---

data/assets/scene/milkyway/exoplanets/exoplanets_data.asset
data/assets/scene/milkyway/exoplanets/exoplanets_textures.asset
modules/exoplanets/exoplanetsmodule.cpp
modules/exoplanets/exoplanetsmodule.h
modules/exoplanets/exoplanetsmodule_lua.inl
openspace.cfg

Also rename 1 Au Ring to 1 Au Circle

Expose exoplanet creation settings to user as module properties

---

data/assets/util/tle_helper.asset
modules/space/rendering/renderableorbitalkepler.cpp
modules/space/rendering/renderableorbitalkepler.h
modules/space/rendering/renderablesatellites.cpp
modules/space/rendering/renderablesatellites.h
modules/space/rendering/renderablesmallbody.cpp
modules/space/rendering/renderablesmallbody.h

Satellites and asteroids are now working with property settings if they are (optionally) specified in asset file. Improved the menu GUI controls for contiguous and dispersed data sampling modes.

Fixes for Issue #1409

---

data/assets/scene/digitaluniverse/stars.asset
data/assets/scene/digitaluniverse/stars_colormap.asset
data/assets/scene/milkyway/exoplanets/exoplanets_data.asset
modules/exoplanets/exoplanetshelper.cpp
modules/exoplanets/exoplanetsmodule.cpp
modules/exoplanets/exoplanetsmodule.h

Also prevent future problems in reading the file (e.g. if number of lines of comments would change)

Remove hardcoded path to B-V colormap

---

data/assets/scene/solarsystem/missions/insight/edl.asset
modules/space/rotation/spicerotation.cpp
modules/space/rotation/spicerotation.h
modules/space/translation/spicetranslation.cpp
modules/space/translation/spicetranslation.h
src/util/spicemanager.cpp
src/util/spicemanager_lua.inl

https://github.com/OpenSpace/OpenSpace/issues/1056

add fixed time for spice translations, update insight asset to use

---

openspace.cfg
src/engine/openspaceengine.cpp
src/rendering/renderengine.cpp

Reduce fontsize of shutdown warning and center it instead with a dimming of the rendering

---

apps/OpenSpace/ext/launcher/CMakeLists.txt

Add support for Qt6

---

include/openspace/navigation/orbitalnavigator.h
src/navigation/orbitalnavigator.cpp

And make property title formatting more consistent throughout OrbitalNavigator
closes #1822

Add bool property to toggle follow anchor node rotation

---

apps/OpenSpace/main.cpp
data/assets/base_blank.asset
data/assets/util/dpiscaling.asset
include/openspace/engine/windowdelegate.h
src/rendering/renderengine.cpp
src/rendering/renderengine_lua.inl

1. Add the ability to query the operating system's DPI scaling values
2. Expose those values through a new Lua function
3. Add an asset that sets the CEF gui and the Dashboard font sizes and placements based on the DPI scaling
4. Add that new asset into the base_blank asset

DPI scaling

---

data/assets/scene/solarsystem/heliosphere/bastille_day/density_volume.asset
data/assets/scene/solarsystem/heliosphere/bastille_day/fieldlines.asset
data/assets/scene/solarsystem/heliosphere/bastille_day/fluxnodes.asset
data/assets/scene/solarsystem/heliosphere/bastille_day/fluxnodescutplane.asset
data/assets/scene/solarsystem/heliosphere/bastille_day/lightindicator.asset
data/assets/scene/solarsystem/planets/earth/magnetosphere/magnetosphere.asset
data/assets/scene/solarsystem/planets/earth/transforms.asset
data/assets/scene/solarsystem/sun/EUV_layer.asset
modules/volume/rendering/renderabletimevaryingvolume.cpp

I tested removing brightness altogether but it's needed.
What do you think about having both properties in the GUI like this? Visually it's difficult to understand the difference.

interaction sphere and brightness/opacity fixes. (Closes #1994)

---

data/assets/scene/solarsystem/missions/jwst/deployment.mission

This only contains the deployment part of the mission since that is the only thing we have data for. Closes #2009

Add .mission file for JWST

---

data/assets/scene/solarsystem/sssb/itokawa.asset

Add Itokawa asset

---

data/assets/scene/solarsystem/planets/saturn/minor/other_group.asset
data/assets/scene/solarsystem/planets/saturn/minor/shepherd_group.asset
data/assets/scene/solarsystem/planets/saturn/minor_moons.asset

Add asset for Shepherd moon group of Saturn system

---

include/openspace/rendering/renderable.h
include/openspace/rendering/renderengine.h
modules/server/src/topics/skybrowsertopic.cpp
modules/skybrowser/include/browser.h
modules/skybrowser/include/renderableskytarget.h
modules/skybrowser/include/screenspaceskybrowser.h
modules/skybrowser/include/targetbrowserpair.h
modules/skybrowser/include/utility.h
modules/skybrowser/include/wwtcommunicator.h
modules/skybrowser/include/wwtdatahandler.h
modules/skybrowser/skybrowsermodule.cpp
modules/skybrowser/skybrowsermodule.h
modules/skybrowser/skybrowsermodule_lua.inl
modules/skybrowser/src/browser.cpp
modules/skybrowser/src/screenspaceskybrowser.cpp
modules/skybrowser/src/targetbrowserpair.cpp
modules/skybrowser/src/utility.cpp
modules/skybrowser/src/wwtcommunicator.cpp
modules/skybrowser/src/wwtdatahandler.cpp
src/rendering/renderable.cpp
src/rendering/renderengine.cpp

This PR does some minor cleanup of the SkyBrowser module but more importantly adds the ability to compare a local hash to a remote hash to perform automatic updating of files.  It also moves the wwtimagedata folder from the modules/skybrowser into the sync folder

SkyBrowser Hash Handling

---

data/assets/util/ipac.asset

Update the Ipac example asset

---

data/assets/scene/solarsystem/missions/jwst/timelapse.asset
data/assets/scene/solarsystem/missions/jwst/toggle_trail.asset
data/assets/scene/solarsystem/missions/jwst/trail.asset
data/assets/scene/solarsystem/planets/earth/lagrange_points/L2.asset
data/profiles/jwst.profile

Add trail that co-revolves with L2 around the Sun.
Also contains some tweaking of trail colors and speeds in the timelapse script.

JWST trail update

---

README.md

Would resolve https://github.com/OpenSpace/OpenSpace/issues/2396 if merged

docs: Adds license to readme

---

data/assets/scene/digitaluniverse/exoplanets.asset
data/assets/scene/solarsystem/missions/apollo/17/bouldersstation6.asset
data/assets/scene/solarsystem/missions/apollo/insignias_map.asset
data/assets/scene/solarsystem/planets/earth/noaa-sos/land/earthquake-1980_1995_quakes.asset
data/assets/scene/solarsystem/planets/earth/noaa-sos/land/land_cover-slideshow.asset
data/assets/scene/solarsystem/planets/earth/noaa-sos/land/surface_temperature.asset
data/assets/scene/solarsystem/planets/earth/noaa-sos/oceans/marine_impacts.asset
data/assets/scene/solarsystem/planets/venus/venus.asset

Just noticed that some assets have multiple keys with for same property.
Creating issue for it so that a PR can be created to check the changes (minor) just in case (due to how close we are to RC for 19.0).

issue/2598 

---

modules/video/include/videoplayer.h
modules/video/src/videoplayer.cpp

Remove from syncable list after destruction; only use one fbo; remove code no longer used

Fix bugs in videoplayer

---

data/profiles/newhorizons.profile

disabling new horizons labels by default

---

data/assets/scene/solarsystem/dwarf_planets/eris/planet.asset
data/assets/scene/solarsystem/dwarf_planets/haumea/planet.asset
data/assets/scene/solarsystem/dwarf_planets/makemake/planet.asset

fixing model scale for dwarf planets

---

modules/atmosphere/rendering/atmospheredeferredcaster.cpp
modules/atmosphere/rendering/atmospheredeferredcaster.h
modules/atmosphere/rendering/renderableatmosphere.cpp
modules/atmosphere/rendering/renderableatmosphere.h

Closes #2759 
I copied some code from the atmosphere shader to be able to calculate the shadow from the eclipse

Show stars during an eclipse

---

modules/skybrowser/skybrowsermodule_lua.inl
src/rendering/screenspacerenderable.cpp

Closes #2504 
The error was that we applied hdr rendering to screenspacerenderables

Fix bug with dark screen space renderables

---

data/assets/educational/scale/gateway_arch.asset
data/assets/educational/scale/golden_gate_bridge.asset

removing old files from comment

updated goldengate and gatewayarch models; update ghoul for cachefix

---

modules/space/translation/keplertranslation.cpp

Allow negative values for KeplerTranslation values

---

src/scene/scenegraphnode.cpp

Render in sticker bin, remove triangle mesh to make it easier to see if one sphere is inside the other, and add a description of which sphere is which
This is how they look for e.g. ISS now (note that the adaptive stereo distance has to be reduced for the rendering to be visible...)
My reason for looking at this is that I want to add more debug render features for scene graph nodes  (next is a representation of the XYZ axes of the model space)

Improve rendering of debug spheres

---

apps/OpenSpace/ext/launcher/src/launcherwindow.cpp
config/equirectangular_gui.json
config/fullscreen1080.json
config/gui_projector.json
config/single.json
config/single_fisheye.json
config/single_fisheye_gui.json
config/single_gui.json
config/single_gui_spout.json
config/single_gui_with_graphics.json
config/single_sbs_stereo.json
config/single_two_win.json
config/spherical_mirror.json
config/spherical_mirror_gui.json
config/spout_output_cubemap.json
config/spout_output_equirectangular.json
config/spout_output_fisheye.json
config/spout_output_flat.json
config/two_nodes.json

As with the profiles, this provides a tool tip description for each config option from the built-in configs. Appears when user hovers over the config filename in the launcher drop-down menu.

Issue/2475 : Tooltip descriptions in launcher for window configs

---

modules/exoplanets/exoplanetshelper.cpp
modules/exoplanets/exoplanetshelper.h
modules/exoplanets/exoplanetsmodule.cpp
modules/exoplanets/exoplanetsmodule.h
modules/exoplanets/exoplanetsmodule_lua.inl
modules/exoplanets/tasks/exoplanetsdatapreparationtask.cpp
modules/exoplanets/tasks/exoplanetsdatapreparationtask.h

Closes #2225 
I just did minimal changes to make it work, but the code might need some restructuring and improvement now that we allow loading files that we are enot as much in control over. 
Some thoughts from my side: 
1. The data-loading logic now lives in the previous data preparation task, but maybe it's worth breaking it out into a separate handler that could be instantiated in the ExopanetsModule? To avoid using static functions in the task for reusing the CSV loading code. 
2. We may also have to validate that all columns we expect to be in the dataset are there. For instance, the inclination is not included per default if one just downloads a data table as is from the Exoplanet Archive, but as we replace it with default values, the user won't know that that data is missing. 
3. …

Issue/2225 - Add exoplanets from a CSV file

---

modules/base/rendering/renderabletrail.cpp

Change name of line fade in RenderableTrail from Fade to LineFade

---

modules/base/rendering/renderablenodeline.cpp
modules/base/rendering/renderableplaneimageonline.cpp
modules/base/rendering/renderableplanetimevaryingimage.cpp
modules/base/rendering/renderablesphereimageonline.cpp
modules/base/rendering/screenspaceimagelocal.cpp
modules/base/rendering/screenspaceimageonline.cpp
modules/cefwebgui/cefwebguimodule.cpp
modules/gaia/rendering/renderablegaiastars.cpp
modules/globebrowsing/src/geojson/geojsoncomponent.cpp
modules/kameleonvolume/rendering/renderablekameleonvolume.cpp
modules/space/horizonsfile.cpp
modules/space/rendering/renderableorbitalkepler.cpp
modules/space/rendering/renderablestars.cpp
modules/video/src/videoplayer.cpp
modules/vislab/rendering/renderabledistancelabel.cpp
src/navigation/pathnavigator.cpp
src/scene/assetmanager.cpp

Ghoul
- AssImp 5.2.4 -> 5.2.5
- Catch2 3.3.1 -> 3.4.0
- fmt    9.1.0 -> 10.1.1
- glbinding  master -> 3.3.0
SGCT
- Catch2 3.3.1 -> 3.4.0
- fmt    9.1.0 -> 10.1.1

Update submodules to fix compilation error on newer Clang and GCC

---

data/assets/scene/solarsystem/planets/earth/layers/colorlayers/modis_terra_chlorophyll_a_temporal.asset

update to new chlorophyll layer from gibs

---

data/assets/util/webgui.asset
include/openspace/navigation/path.h
include/openspace/navigation/pathnavigator.h
modules/server/CMakeLists.txt
modules/server/include/topics/camerapathtopic.h
modules/server/include/topics/cameratopic.h
modules/server/include/topics/skybrowsertopic.h
modules/server/include/topics/timetopic.h
modules/server/src/connection.cpp
modules/server/src/topics/camerapathtopic.cpp
modules/server/src/topics/cameratopic.cpp
src/navigation/path.cpp
src/navigation/pathnavigator.cpp

Related to WebGui PR: https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/compare/issue%2F2665?expand=1
Closes #2665

Issue/2665 - Show timer for how long time left in camera path

---

include/openspace/navigation/waypoint.h
src/navigation/pathnavigator.cpp
src/navigation/waypoint.cpp

Keep track of aim from navigation state when creating a camera path

---

data/assets/scene/milkyway/constellations/big_dipper.asset

[bigdipper_constellation_data.zip](https://github.com/OpenSpace/OpenSpace/files/14845576/bigdipper_constellation_data.zip)

Added asset showing only the Big Dipper

---

data/assets/actions/time.asset

wont work when paused until https://github.com/OpenSpace/OpenSpace/issues/3158 is fixed.
Closes #2106

Added time reversal and sidereal actions

---

data/profiles/voyager.profile

Disable minor moons of Jupiter and Saturn on Voyager profile startup

---

data/assets/scene/solarsystem/missions/voyager/voyager1.asset
data/assets/scene/solarsystem/missions/voyager/voyager2.asset

The "box" in the model was baked into the obj model files, so the solution for this issue is to update the model to be in one piece instead of in many smaller pieces that we used to have.
The new model needs to be uploaded to our servers: 
[Voyager.zip](https://github.com/OpenSpace/OpenSpace/files/15197904/Voyager.zip)
Something to discuss could be the scale and size of the spacecraft. According to a quick search, the spacecraft is rather small (about 2.5 meters with the antenna). The model, right now, looks to be much larger than that but it does match up with the model we previously had with the "box" inside it. Do we want to update it to be in the correct size? Then we would have a similar issue as with another model in that it is too small to get up close to it without turning off or …

Update Voyager Model, closes #3035

---

data/assets/examples/scale/luascale/example.lua
data/assets/examples/scale/luascale/lua.asset
modules/base/scale/luascale.cpp
modules/base/scale/luascale.h

Adding documentation for the LuaScale class and fixing some issues with it while already in the code

Add example for the LuaScale class and fix it at the same time

---

src/network/parallelpeer.cpp
src/network/parallelpeer_lua.inl

Includes the necessary server info to join a parallel connection, however does not include the buffer time, and keyframe intervals. 
Also fixes the disconnect function calling connect (?)

Adds a join server lua function for parallelpeer

---

data/assets/scene/solarsystem/sssb/amor_asteroid.asset
data/assets/scene/solarsystem/sssb/apollo_asteroid.asset
data/assets/scene/solarsystem/sssb/aten_asteroid.asset
data/assets/scene/solarsystem/sssb/atira_asteroid.asset
data/assets/scene/solarsystem/sssb/centaur_asteroid.asset
data/assets/scene/solarsystem/sssb/chiron-type_comet.asset
data/assets/scene/solarsystem/sssb/encke-type_comet.asset
data/assets/scene/solarsystem/sssb/halley-type_comet.asset
data/assets/scene/solarsystem/sssb/inner_main_belt_asteroid.asset
data/assets/scene/solarsystem/sssb/jupiter-family_comet.asset
data/assets/scene/solarsystem/sssb/jupiter_trojan_asteroid.asset
data/assets/scene/solarsystem/sssb/main_belt_asteroid.asset
data/assets/scene/solarsystem/sssb/mars-crossing_asteroid.asset
data/assets/scene/solarsystem/sssb/outer_main_belt_asteroid.asset
data/assets/scene/solarsystem/sssb/pha.asset
data/assets/scene/solarsystem/sssb/transneptunian_object_asteroid.asset

This updates the SSSB asteroids/comets with the latest Horizons kepler element data as of May 2024.
This bumps the file version to v4 for these data.
Currently, only the Utah data server has the v4 files.
Closes #3173

Update sssb data for asteroids/comets

---

data/assets/modules/exoplanets/exoplanets_data.asset

Need the files to be uploaded by @alexanderbock 
Closes https://github.com/OpenSpace/OpenSpace/issues/3172

Update exoplanet data

---

modules/globebrowsing/scripts/layer_support.lua

This is a pull request to be put into this one: https://github.com/OpenSpace/OpenSpace/pull/3281

added zIndex parsing for .info files

---

data/assets/examples/renderable/renderablepointcloud/pointcloud_textured.asset
data/assets/examples/renderable/renderablepointcloud/pointcloud_textured_facecameraposition.asset

Note that it is really difficult to see what is going on without a texture, so added a texture to this example as well.

Add a point cloud example that changes the point orientation

---

modules/exoplanets/exoplanetsmodule_lua.inl

Needs input on if the size and fading of the label is good.  For now I just used the same as the one we have for our Sun. 
The label is disabled per default. Maybe we want a setting for controlling this?
closes #3318

Add a Label for Exoplanet Systems (Issue #3318)

---

modules/exoplanets/exoplanetsmodule.cpp
modules/exoplanets/exoplanetsmodule.h
modules/exoplanets/exoplanetsmodule_lua.inl

Add a similar setting like we have for the stars
closes #3280

Add option to specify a default texture for added exoplanets

---

apps/OpenSpace/CMakeLists.txt
apps/OpenSpace/ext/launcher/src/launcherwindow.cpp
apps/OpenSpace/ext/launcher/src/profile/assettreeitem.cpp

To check here is whether this still compiles with older Qt version.  Whoever tests this, please put your Qt version in a post so that we can determine what the minimum version is

Update to newer Qt version

---

modules/webbrowser/cmake/patch/cmake/cef_variables.cmake
modules/webbrowser/include/webrenderhandler.h
modules/webbrowser/src/webrenderhandler.cpp

Fixes for linux build with most recent CEF update

---

modules/base/dashboard/dashboarditemelapsedtime.cpp

This PR fixes 3 bugs related to the "elapsed time" dashboard: #3519, #3515, #3516.

Fixes for some "elapsed time" dashboard bugs

---

apps/OpenSpace/ext/launcher/src/profile/horizonsdialog.cpp
src/navigation/navigationstate.cpp

this fixes compilation with GCC 14.2.1

add a cast from json to std::string for anchor

---

data/assets/examples/scale/timelinescale/no-interpolate.asset
data/assets/examples/scale/timelinescale/timeline.asset
modules/base/CMakeLists.txt
modules/base/basemodule.cpp
modules/base/scale/timelinescale.cpp
modules/base/scale/timelinescale.h

There already was a TimelineTranslation and TimelineRotation, so adding this for symmetry

Add new class TimelineScale

---

modules/space/rendering/renderablestars.cpp
modules/space/rendering/renderablestars.h
modules/space/shaders/star_ge.glsl
modules/space/shaders/star_vs.glsl

Where provided, the RenderableStars now uses the velocity information to propagate the stars' position properly
Closes #562

Add proper motion of stars

---

include/openspace/scene/assetmanager.h
src/scene/assetmanager.cpp
src/scene/assetmanager_lua.inl

Reloads an asset by removing it and adding its new definition back.

assetmanager: add a 'reload' function, available as a scripting API

---

apps/OpenSpace/ext/launcher/include/profile/timedialog.h
apps/OpenSpace/ext/launcher/src/profile/timedialog.cpp

Turn the time selector in the Profile Editor into a tabbed window

---

data/assets/scene/solarsystem/planets/saturn/titan/layers/colorlayers/cassini_sar_hisar_global_mosaic_351m_sweden.asset
data/assets/scene/solarsystem/planets/saturn/titan/layers/colorlayers/cassini_sar_hisar_global_mosaic_351m_sweden.wms

Awaiting verification by Carter
Closes #1628

Add Titan HiSAR Mosaic WMS layer

---

apps/OpenSpace/ext/launcher/include/sgctedit/windowcontrol.h
apps/OpenSpace/ext/launcher/src/sgctedit/displaywindowunion.cpp
apps/OpenSpace/ext/launcher/src/sgctedit/windowcontrol.cpp

- Adds the ability to control the fisheye tilt for Fisheye projections
- Adds the ability to blit the contents of another window
Closes #3468
Closes #3469

Add tilt and window blitting options to the Launcher

---

src/CMakeLists.txt

Thanks for @wtbgagoa for the initial patch for this!
Closes #3624

Compile fix for Linux arch

---

include/openspace/query/query.h
src/query/query.cpp
src/scene/scene.cpp
src/scene/scene_lua.inl
tests/CMakeLists.txt
tests/test_lua_property.cpp
tests/test_lua_propertyvalue.cpp
tests/test_lua_setpropertyvalue.cpp

Also adds unit tests to ensure the setPropertyValue/setPropertyValueSingle/getPropertyValue/property functions still work.
Closes #3588. Closes #3260. Closes #1755

Cleaning up the code for the setProperty value functions, add better documentation, and add the ability to combine tags

---

data/assets/util/static_server.asset
data/assets/util/webgui.asset
openspace.cfg

Adding the code that integrates the ShowComposer into OpenSpace

ShowComposer

---

modules/server/src/topics/profiletopic.cpp

Adds a boolean telling if the software has been started before to the profile topic.
To be used with this PR: https://github.com/OpenSpace/OpenSpace-WebGui/pull/161
Closes #3045

Show getting started tour on startup

---

data/assets/actions/trails/on_off_all_minor_moons.asset
data/assets/scene/solarsystem/heliosphere/bastille_day/fieldlines.asset
data/assets/scene/solarsystem/heliosphere/bastille_day/fluxnodes.asset
data/assets/scene/solarsystem/heliosphere/bastille_day/fluxnodescutplane.asset
data/assets/scene/solarsystem/heliosphere/bastille_day/fluxnodeslegend.asset
data/assets/scene/solarsystem/missions/apollo/apollo_globebrowsing.asset
data/assets/scene/solarsystem/missions/newhorizons/actions.asset
data/assets/scene/solarsystem/missions/osirisrex/actions.asset
data/assets/scene/solarsystem/missions/rosetta/rosetta.asset
data/assets/scene/solarsystem/planets/jupiter/minor_moons.asset
data/assets/scene/solarsystem/sun/euv_layer.asset

Fixes some issues with toggling not working if the object is faded out.

Utilize `toggleFade` function to clean up some toggle actions

---

data/assets/actions/planets/planet_lighting.asset

Apply "All globes" illumination action to all RenderableGlobes

---

data/assets/nightsky/galactic_band.asset

Fixes changes from rename of galactic line/band to equator
