- apps/Launcher/main.cpp
This is a simple alteration to how Launcher checkboxes display status; green indicates a check, whereas red does not.
This is an attempt to deal with [Issue #155.](https://github.com/OpenSpace/OpenSpace/issues/155)
> Modification to Launcher checkboxes - clearly defined status-indicators.

- apps/Launcher/syncwidget.cpp
This now works, and builds on Jenkins on all platforms.
> * When Launcher first starts only the default scene is selected.

- include/openspace/properties/property.h
- openspace.cfg
- src/properties/property.cpp
`Visibility::None` caused a compile error on Linux, since x11 defines the macro None. (https://github.com/aseprite/aseprite/issues/482). Changed None to Hidden.
This seems to have been accidentally pushed ?
`OPENSPACE_DATA = "${BASE_PATH}/data-minimal",`
changed back to `${BASE_PATH}/data`
> Rename None to Hidden, to avoid collision with X11 and reset data path

- apps/Launcher/ext/libtorrent/CMakeLists.txt
Remove if guard on libtorrent's find_package(Boost). Enable Boost multithreading.
closes #340
> Remove if guard on libtorrent's find_package(Boost).

- src/performance/performancemanager.cpp
even when there is not a multiple of the PerformanceLayout::NumberValues
> Write remaining PerformanceMeasurement logs on destruction

- modules/globebrowsing/rendering/chunkrenderer.cpp
- modules/globebrowsing/shaders/tileheight.hglsl
Fix previous error appearing when accurate normals were used without height layers.
> Small Globe Normal Fix

- modules/imgui/src/renderproperties.cpp
Do not assume that string propeties are file paths.
Fix proper escaping in lua script generation.
Fixes https://github.com/OpenSpace/OpenSpace/issues/420
> StringProperty fix

- apps/OpenSpace/main.cpp
Make use of new sync parametrization to disable messages and set waitout time to 15 minutes (closes #488)
> Update sgct repository

- modules/space/shaders/star_vs.glsl
Fixed error when rendering old stars renderable without the Milky Way sphere renderable.
> Fixed issue 435.

- data/assets/dawn.scene
- data/assets/default.scene
- data/assets/juno.scene
- data/assets/newhorizons.scene
- data/assets/osirisrex.scene
- data/assets/rosetta.scene
- data/assets/util/asset_helper.asset
- data/assets/util/default_dashboard.asset
- data/assets/voyager.scene
- include/openspace/rendering/dashboard.h
- include/openspace/rendering/dashboarditem.h
- modules/base/dashboard/dashboarditemangle.cpp
- modules/base/dashboard/dashboarditemdate.cpp
- modules/base/dashboard/dashboarditemdistance.cpp
- modules/base/dashboard/dashboarditemframerate.cpp
- modules/base/dashboard/dashboarditemmission.cpp
- modules/base/dashboard/dashboarditemparallelconnection.cpp
- modules/base/dashboard/dashboarditemsimulationincrement.cpp
- modules/base/dashboard/dashboarditemspacing.cpp
- modules/base/rendering/screenspacedashboard.cpp
- modules/spacecraftinstruments/dashboard/dashboarditeminstruments.cpp
- scripts/core_scripts.lua
- src/mission/missionmanager.cpp
- src/rendering/dashboard.cpp
- src/rendering/dashboard_lua.inl
- src/rendering/dashboarditem.cpp
Turn the default dashboard items into an asset, to avoid copies of the same dashboard items when loading and unloading scenes.
Breaking change: removed `openspace.setDefaultDashboard` from `core_scripts`.
To load default dashboard, instead use: `asset.require('util/default_dashboard')`
> Fix DashboardItem bugs related to unloading and loading assets at runtime

- src/engine/configuration.cpp
@micahnyc pointed out that when double clicking an application on mac, the current working directory is set to "/". One way to get around this problem would be to set cwd to the application path, using NSGetExecutablePath. However, instead, I suggest that we don't change the current working directory, and use the newly introduced ${BIN} to find the configuration file.
Let me know what your thoughts are. I have only tested this on mac yet.
> Use bin folder instead of cwd to find configuration file

- apps/OpenSpace/main.cpp
- include/openspace/engine/globalscallbacks.h
- include/openspace/engine/openspaceengine.h
- modules/imgui/imguimodule.cpp
- modules/webbrowser/include/eventhandler.h
- modules/webbrowser/src/eventhandler.cpp
- src/engine/globalscallbacks.cpp
- src/engine/openspaceengine.cpp
Depends on https://github.com/opensgct/sgct/pull/26
Enables correct keyboard modifier information to be passed to CEF on mouse clicks events.
> Pass on modifier keys to CEF for mouse events

- src/interaction/mousecamerastates.cpp
* Holding Ctrl while zooming with the Right mouse button or Alt-Left mouse will now increase the sensitivity, causing the zoom speed (in or out) to increase by 8x
* Likewise, holding Shift while zooming will decrease the sensitivity by 2x (1/2 of the speed)
* These values are different as zooming is already relatively insensitive, and it seems likely (?) that the user won't want to make it much less insensitive when holding down Shift
* These are hardcoded values but ideally should later be made configurable, e.g. via the Orbital Navigator sliders
* This is related to issue #709, although it allows for both speeding up and down rather than just slowing down
* Thanks to Micah for his support during the hackathon!
> Add support for zoom sensitivity adjustment with Ctrl/Shift

- config/single.xml
- config/single_gui.xml
- config/single_two_win.xml
- config/spherical_mirror_gui.xml
- config/two_nodes.xml
- openspace.cfg
Fix for : https://github.com/OpenSpace/OpenSpace/issues/893
Figured that it made sense for the FOVs of these files to match what the default window has.
Also removed the spout stuff from the default full screen since we have a spout example below it for obs.
> added viewport tracking to configs

- include/openspace/rendering/screenspacerenderable.h
- modules/base/rendering/screenspacedashboard.cpp
- modules/base/rendering/screenspaceframebuffer.cpp
- modules/base/shaders/screenspace_fs.glsl
- modules/webbrowser/src/screenspacebrowser.cpp
- src/rendering/screenspacerenderable.cpp
Screenspace renderables used to overcompensate for screen aspect ratio. This is fixed in this commit.
Also removed unused uniform OcclusionDepth.
> Fix scaling issue with screenspace renderables

- src/scene/assetloader.cpp
This worked for allowing me to remove more than one asset in the console.
> Change AssetLoader unloadAsset to clear init/deinitialization functions for only one asset

- include/openspace/interaction/orbitalnavigator.h
- src/interaction/externinteraction.cpp
- src/interaction/navigationhandler.cpp
- src/interaction/orbitalnavigator.cpp
- src/network/parallelpeer.cpp
I have addressed the major jump descrived in https://github.com/OpenSpace/OpenSpace/issues/940 in master, but there was a smaller camera movement related to remaining values in the follow anchor node interpolator. To solve this, the interpolator is reset whenever there is a new anchor node. I implemented this in `resetVelocities` which is also called when applying a new navigation state, and when leaving keyframe navigation mode etc.
> Cancel follow anchor node rotation interpolation when the anchor is changed

- modules/touch/CMakeLists.txt
- modules/touch/include/directinputsolver.h
- modules/touch/include/touchinteraction.h
- modules/touch/src/directinputsolver.cpp
- modules/touch/src/touchinteraction.cpp
- modules/touch/src/win32_touch.cpp
- modules/touch/touchmodule.cpp
Fixed rotation matrices in the touchmodule, while at it I also moved out
the lev-marq solver from the touchinteraction.cpp to its own file, in an
effort to make the code lighter to read.
Also changed some logic in how touch intersection is made with the
scenenodes.
fixes issue #1019 
- Touchmodule now accounts for increments in simulation time
> Issue/1019 - Fixed rotation matrices in touch

- modules/base/rendering/renderablelabels.cpp
Just a quick fix to be able to compile on Linux which is case sensitive.
> fix case sensitive include file for linux compile

- src/engine/downloadmanager.cpp
- src/util/httprequest.cpp
This will make it possible to build OpenSpace on a Linux OS with an older curl version. The curl progress will not be shown on the splash screen but will instead be outputted in the console. I have verified that the download works on both cases on Linux.
> support curl version < 7.32.0, i.e. rhel/centos 7

- apps/OpenSpace/main.cpp
- config/single_sbs_stereo.xml
- include/openspace/engine/windowdelegate.h
- modules/base/rendering/screenspacedashboard.cpp
- modules/base/rendering/screenspaceframebuffer.cpp
- modules/cefwebgui/cefwebguimodule.cpp
- modules/digitaluniverse/rendering/renderablebillboardscloud.cpp
- modules/imgui/imguimodule.cpp
- modules/webbrowser/include/browserinstance.h
- modules/webbrowser/src/browserinstance.cpp
- openspace.cfg
- src/rendering/framebufferrenderer.cpp
- src/rendering/loadingscreen.cpp
- src/rendering/luaconsole.cpp
- src/rendering/renderengine.cpp
- src/rendering/screenspacerenderable.cpp
- src/scene/scenegraphnode.cpp
- src/util/touch.cpp
Fixed issue 1049(using first viewport size as framebuffer size) and 554(loading and ending screen will be visible on the first viewport only). Also fixed such that Lua Console adapts to window size and not framebuffer size.
Tested with multiple configs, and zoom through the cosmos (milky way etc)
> Fixed issue 1049 and 554 (multiple viewport problems and lua console scales)

- include/openspace/util/touch.h
This should fix builds since another version of glm handles these include paths somewhat differently.
> Changed glm include path

- modules/base/rendering/renderablelabels.cpp
- modules/base/rendering/renderablelabels.h
- modules/vislab/rendering/renderabledistancelabel.cpp
- modules/vislab/rendering/renderabledistancelabel.h
This adds a way to customize the way how distances are shown on distance labels. It is possible to config the used unit (out of the existent openspace units, for example "gigameter"), and it is possible to set a custom descriptor. For SPVL for example we are using gigameter and the descriptor "million km" since we see that the average museum visitor has limited understanding to grasp "gigameter" and kilometer values are getting too big.
> Added a way to customize renderable distance labels unit

- modules/webbrowser/include/browserinstance.h
- modules/webbrowser/include/eventhandler.h
- modules/webbrowser/src/browserinstance.cpp
- modules/webbrowser/src/eventhandler.cpp
Enabled cef touch events instead of injected mouse events for the CEF-part. 
Should be the same as https://github.com/OpenSpace/OpenSpace/pull/1087
> cef touch events for spvl project branch

- modules/webbrowser/include/browserinstance.h
- modules/webbrowser/include/eventhandler.h
- modules/webbrowser/src/browserinstance.cpp
- modules/webbrowser/src/eventhandler.cpp
This PR changes the internal behaviour of the Cef webbrowser to treat touch events as true touch points (cef-wise) rather than as an injected mouse event.
This means that scrolling in menus, panning and potentially zooming of canvases should be possible through the means of touch.
For this to work, a newer CEF version than the one OSX currently uses is required. However, bumping CEF is not included in this PR, so touch is treated as injected mouse events on mac.
> Changed webbrowser to use cef touch events

- apps/OpenSpace/main.cpp
@jccosta I think this just ended up here by accident.  Was unable to compile without removing the superfluous #endif
> Fix Linux Fixes

- modules/exoplanets/exoplanetshelper.cpp
- modules/exoplanets/exoplanetshelper.h
- modules/exoplanets/exoplanetsmodule_lua.inl
- modules/exoplanets/shaders/orbitdisc_fs.glsl
- src/scene/scene.cpp
- src/scene/scene_lua.inl
Fixes to handle problems with problematic data, e.g. angles outside [0, 360] or with problematic names. Also, don't include exoplanet systems without sufficient data in the GUI list. 
Also, `removeSceneGraphNode` had problems with identifiers with e.g. plus signs in them since it was based on a regex match. Implemented so that the regular removal just finds the node with the specified identifier and made the regex removal its own function
There are still about 30 systems in the GUI list that cannot be added, due to missing data in a subset of the exoplanets in the system. I was thinking of hacking together something quick to solve this, but want to make a neater solution for handling systems with insufficient data... So that will be left until after the release
> Exoplanets - fixes to avoid errors when adding/removing systems

- modules/base/rendering/renderableplaneimageonline.cpp
- modules/base/rendering/screenspaceimageonline.cpp
Added to Ghoul TextureReader an exception throw if `loadTexture` fails. This covers uses of the `loadTexture(memory, size, format)` overload that didn't throw an exception.
> Fix for crash if screenspace image load fails

- include/openspace/rendering/screenspacerenderable.h
- src/rendering/screenspacerenderable.cpp
Missed during opacity rewrite. Don't think we need to notify the users of this change, since we kind of already did?
> Rename ScreenSpaceRenderable alpha to opacity (closes #1416)

- modules/globebrowsing/src/renderableglobe.cpp
The globebrowsing shader code was being compiled with support for accurate normals even when the data required (the height layer) wasn't available.
Now, the shader code is only added if the height information is available.
> Fixed issue 1382: Enabling accurate normals when the height layer info wasn't available.

- data/assets/scene/digitaluniverse/exoplanets.asset
- modules/exoplanets/exoplanetshelper.cpp
- modules/exoplanets/exoplanetshelper.h
- modules/exoplanets/exoplanetsmodule_lua.inl
- modules/exoplanets/tasks/exoplanetsdatapreparationtask.cpp
- Exoplanet code cleanup (ugly matching of names in speck file)
- Now possible to add exoplanet systems where one or a few planets are having insufficient data. Good for example for the Kepler-80 system, where there is enough data for 5/6 exoplanets (previously this one could not be added at all)
> Exoplanets cleanup

- ext/json/json.hpp
Simply updating json.hpp to 3.9.1 fixes linux build for gcc10 (also works for gcc9). Works on windows also.
> Updated ext/json to 3.9.1 to fix gcc10 build

- modules/globebrowsing/src/renderableglobe.cpp
This only adds the properties related to the eclipse to the globe if the data needed for the eclipse is available.
> Issue 1516

- src/rendering/renderable.cpp
Addressing https://github.com/OpenSpace/OpenSpace/issues/1484 
When changing the opacity of a trail, it's renderbin was also being changed by the default renderable behavior. 
we already had a case to prevent this default behavior to renderables that are marked as RenderBin::PostDeferredTransparent
so I add ones that are marked as RenderBin::Overlay to this case. 
This changes ultimately changes the order in which the trail will be rendered here: https://github.com/OpenSpace/OpenSpace/blob/cdbc1c2695b90fe1b9af1b40e5fd6ed8b577ecf1/src/rendering/framebufferrenderer.cpp#L1137 and thus making it 'not interact' with the atmosphere
> prevent renderbin change for overlay renderables

- apps/OpenSpace/main.cpp
- include/openspace/rendering/renderengine.h
- src/rendering/renderengine.cpp
Closes #1528 
Question:
As implemented right now the date that is used is *not* the startup time, but the time when the value was set to true.  This means that if you toggle the value on an off, there will then be two folders which will separate the screenshots.
Is this what we want?  I'd say yes since I can't see of a good reason why you'd want to turn on and off the date-addition otherwise
> Add property to determine whether the date should be added to the screenshot folder

- modules/globebrowsing/src/timequantizer.cpp
- tests/test_timequantizer.cpp
Timequantizer still requires start/end days to be in 1-28 range for monthly increment, but allows the full day range for any other increment.
> Fix that allows all days of month except monthly increment still at 1-28

- data/assets/scene/solarsystem/missions/osirisrex/bennu.asset
- data/assets/scene/solarsystem/missions/osirisrex/osirisrex.asset
Adds the hi-res Bennu model from here:
https://www.asteroidmission.org/updated-bennu-shape-model-3d-files/
to the osirisrex mission. The profile has the **BennuProjection** scenegraph node, which is the original low-res Bennu model that gets images projected onto it. This new **Bennu** scenegraph node is disabled by default, but looks much better than the original.
The Utah data server has these 2 new files:
http://openspace.sci.utah.edu/files/solarsystem/missions/osirisrex/bennu/models/v1_v2/Bennu_v20_200k_an.obj
http://openspace.sci.utah.edu/files/solarsystem/missions/osirisrex/bennu/models/v1_v2/Bennu_v20_200k_an.mtl
which will need to be added to the data.openspaceproject.com server.
> Adding hi-res 75cm Bennu model from asteroidmission.org

- include/openspace/properties/numericalproperty.inl
- src/scene/scenegraphnode.cpp
Temporary fix to address #1656. Actually fixing the sliders requires some more careful work and design decisions
> Avoid non-supported ranges for exponential slider

- modules/globebrowsing/globebrowsingmodule.cpp
- modules/globebrowsing/globebrowsingmodule_lua.inl
New name: getLocalPositionFromGeo
This name actually corresponds to what the function does: Computes a cartesian position in the globe's local coordinate system that corresponds to the given Geo position (lat, long, altitude)
> Update faulty docs and function name for globebrowsing.getGeoPosition (#1662)

- apps/OpenSpace/ext/launcher/include/profile/keybindingsdialog.h
- apps/OpenSpace/ext/launcher/src/profile/keybindingsdialog.cpp
Fix for issue #1461: Warns user of duplicate selections for keybindings in profile editor, but still allows the assignment.
> Added warning to keybinding editor for duplicate assignments

- apps/OpenSpace/ext/launcher/include/filesystemaccess.h
- apps/OpenSpace/ext/launcher/src/filesystemaccess.cpp
- apps/OpenSpace/ext/launcher/src/profile/assettreemodel.cpp
This allows any .asset file contained in ${ASSETS} or ${USER_ASSETS} to be displayed in the asset selection GUI.
The previous version of filesystemaccess that accepts a list of approved paths is retained in an overloaded constructor for future use.
> Fix for issue #1739 to prevent filtering of paths in asset directories

- modules/globebrowsing/src/layergroup.cpp
The layer group might not yet be initialized when a layer is added, which leads to an exception when trying to find information about the layer group's layer manage and SGN for the event payload.
> Temporary fix for exception when adding exoplanet systems

- modules/webbrowser/CMakeLists.txt
- modules/webbrowser/cmake/patch/cmake/cef_variables.cmake
- modules/webbrowser/cmake/webbrowser_helpers.cmake
- modules/webbrowser/include/defaultbrowserlauncher.h
- modules/webbrowser/src/browserinstance.cpp
- modules/webbrowser/src/defaultbrowserlauncher.cpp
- modules/webbrowser/src/screenspacebrowser.cpp
- modules/webbrowser/src/webbrowserapp.cpp
There is an issue with the text fields in our gui after this update which needs to be addressed in the -WebGuiFrontend
When using the search fields, sometimes keyevents are sent through to openspace. When using a non search field (such as naming session recording, key events are never sent to openspace. 
In addition, if you check a box or use a slider, then use a search field, then the keyevents are not sent to openspace. 
I'm guessing there is a special behavior on how we have addressed the search fields in react which needs to be updated.
> update cef and a few calls for it

- include/openspace/navigation/path.h
- include/openspace/navigation/pathnavigator.h
- src/navigation/path.cpp
- src/navigation/pathnavigator.cpp
1. Avoids problems with speed when inside big bounding spheres, 
2. updates the speed dampening when bounding spheres are huge and
3. Use time-based interpolation of rotation for linear paths, and don't finish path until both rotation and position interpolation has finished. 
2. leads to abrupt stops when traveling vast distances, to objects with big bounding spheres. There should probably be some improvement made, eventually
3. Decided to keep the old code commented out for now. It will have to be improved to work ish for navigation states eventually. Note that it also broke the debug rendering of the camera view direction, as that assumes that interpolation is done based on distance. No biggie, though, and can be fixed later.
> Camera path updates (#1919 and #1947)

- src/navigation/path.cpp
Glm::equal is not enough to check if two quaternions represent the same orientation.
> Fix the fix for camera rotation not finished at end of path

- include/openspace/engine/globals.h
- src/engine/globals.cpp
- src/scene/scene.cpp
- src/scene/scene_lua.inl
Add the ability to add user-defined properties into the system;
`openspace.addCustomProperty` takes between 2 and 5 arguments:
1. The identifier of the new property
2. The Type of the new property (same naming as the C++ types)
3. The GUI name of the property
4. The Description of the property
5. A Lua script that is called when the property is changed.  The new value is inserted into this script as the `value` parameter;
For example:
`openspace.addCustomProperty("example", "IntProperty", "Example", "This is an example property", [[ if value > 0.0 then openspace.printInfo(value) else openspace.printError(value) end ]])`
Right now there is no way to specify the minimum/maximum values of the new Property;  that is part of #1529 to add that capability to this functionality.
> User Properties

- data/assets/scene/solarsystem/planets/earth/satellites/misc/iss.asset
- modules/base/rotation/fixedrotation.cpp
- modules/base/rotation/fixedrotation.h
This fixes the symptom of issue #1751, and also covers some edge cases when a node transformation might update even if the simulation time is not running. 
However, I suspect that this issue might return as the underlying cause seems to have been that the check against the cached time in the general `Rotation::update` function does not trigger correctly if time is paused: https://github.com/OpenSpace/OpenSpace/blob/0c042369934f34b55c34003673e5969698574675/src/scene/rotation.cpp#L82
(Wondering if the `UpdateData` might not be correctly updated, for some reason, when the time is paused 🤔 Anyhow, that might need more investigation). Open to ideas!
> FixedRotation that depends on other nodes now updates correctly even if time is paused

- data/assets/scene/solarsystem/heliosphere/2012/reset_loop_action.asset
- data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
- data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_enlil.asset
- data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_pfss.asset
- data/assets/scene/solarsystem/planets/earth/magnetosphere/magnetosphere.asset
- data/profiles/solarstorm2012.profile
- modules/fieldlinessequence/rendering/renderablefieldlinessequence.cpp
- modules/fieldlinessequence/rendering/renderablefieldlinessequence.h
- openspace.cfg
This creates a new public profile for the 2012 july solar storm event, with ENLIL, PFSS and BATSRUS models.
Only thing I can think of is to set camera position better. How can I find the current camera position, so that I can copy it ?
Needs to be added to list of profile in .cfg also.
> a new profile for the 2012 solar storm event, with looping hotkeys

- modules/sync/syncs/urlsynchronization.cpp
Before it would download all the files to the same location based on the first file's name in the list.
> Fix filename when downloading multiple files in urlsync

- modules/skybrowser/skybrowsermodule.cpp
- modules/skybrowser/skybrowsermodule_lua.inl
and throw warning if setting to non-existing node
> Disable hover circle per default when setting a renderable (fixes #2153)

- data/assets/scene/digitaluniverse/grids.asset
- modules/base/rendering/grids/renderablegrid.cpp
- modules/base/rendering/grids/renderablegrid.h
- modules/base/shaders/grid_vs.glsl
- src/rendering/renderable.cpp
Add the possibility to, for example, highlight every 5th line in the grid with a thicker line and/or a different color. 
The previous `RenderableDUMeshes` grids have now been converted to use the `RenderableGrid` class instead.
Closes #1683
> Enable highlights in grids

- modules/space/rendering/renderableorbitalkepler.cpp
A properties change in a RenderableOrbitalKepler will call updateBuffers but not call initializeGL
> Renderable prop change updates buffers without reinitializing GL

- modules/skybrowser/include/screenspaceskybrowser.h
- modules/skybrowser/src/screenspaceskybrowser.cpp
This PR adds a timer to the scale onChange function that allows the browser to load for 25 frame updates before applying the border radius change.
> Fix for issue of scaling doesn't update border radius

- apps/OpenSpace/ext/launcher/src/launcherwindow.cpp
closes #2207
Note that this is a minimal and pretty naive solution. The profile loading is done on the fly and takes a little while so the tooltips are not immediately available when opening the launcher. Open to suggestions on how to improve it.
Some styling might also be nice
> Add info tooltips to profile selector dropdown in launcher

- src/navigation/path.cpp
- src/navigation/pathcurves/avoidcollisioncurve.cpp
- src/navigation/pathnavigator.cpp
- src/util/collisionhelper.cpp
A collection of fixes for precision-related issues, all discovered when trying to address #2212. This is one of the most troublesome cases for the camera paths; Flying to a small (close to zero-bounding sphere) object far out in space. The position coordinates are so large that we can't always do the computations for the paths with sufficient precision. This PR adds a few checks for that in problematic situations
Also note that the RadialGrids do not get a valid bounding sphere computed until the first time they are enabled, which was why the problem appeared for the 1 AU size rings for the exoplanet systems specifically. Everything works better if the objects have correctly sized bounding spheres. 
Closes #2212, and probably also solves the "shaky" movements that users have reported when …
> Various precision fixes for camera paths

- include/openspace/engine/openspaceengine.h
- src/engine/openspaceengine.cpp
Solves problem with double inputs when using touch interaction
Please let me know if the property description makes sense
> Add property to disable all mouse input in OpenSpace engine

- apps/OpenSpace/ext/launcher/include/profile/actiondialog.h
- apps/OpenSpace/ext/launcher/src/profile/actiondialog.cpp
In order to save entries in the "Actions and Keybindings" dialog of the profile editor, both the Actions and Keybindings sections must be in a valid state. This means that they must not have an incomplete entry being changed or added (clicking Save in the section will transition to a valid state).
> Fix to prevent invalid entries for action or keybinding  in profile edit

- apps/OpenSpace/main.cpp
Fix for issue #2371, so that setting the field-of-view in one window (e.g. GUI window) will apply this setting to all windows (the reason for the issue is that the FOV change is applied only to the non-rendering GUI window).
This will help with the common scenario where one window only has the GUI (no rendering), and a second window is used for an external display.
Note that it may not be desirable to change the FOV on all windows. Another approach to fix this could be to tailor it only to the GUI-window scenario (e.g. **single_gui.json**, **gui_projector.json**), and look for a window with a "GUI" tag as is done [here](https://github.com/OpenSpace/OpenSpace/blob/f6988ea5b0e1e2816deca281069028d965f919f4/apps/OpenSpace/main.cpp#L816).
Please add a comment to this PR if you feel the second …
> Apply FOV changes to all windows rather than only the first window

- modules/skybrowser/include/browser.h
- modules/skybrowser/include/screenspaceskybrowser.h
- modules/skybrowser/src/browser.cpp
- modules/skybrowser/src/screenspaceskybrowser.cpp
* Removed some functionality that was "too smart" and a bit unnecessary. The class adjusted its texture depending on window resolution etc, which is not ideal in a cluster setup
* Removed unused functions and variables
* Moved functions to classes where they made more sense
> Fix bug for screenspace sky browser scale crash

- apps/OpenSpace/ext/launcher/include/profile/actiondialog.h
- apps/OpenSpace/ext/launcher/src/profile/actiondialog.cpp
In the profile editor for actions & keybindings: Switched from main save & cancel buttons to a single "Close" button. This new button doesn't really do anything, because of changes to save behavior in the actions and keybindings sections. Pressing Save in either of those sections will save the corresponding data.
The new Close button is necessary to be consistent with other editor dialog windows, because otherwise the user would have to manually X-close the window.
> Replace profile actions/keybind editor button with single close button

- apps/OpenSpace/ext/launcher/src/sgctedit/sgctedit.cpp
- config/gui_projector.json
Removes our usage of "monitor" key in sgct config files, but does not remove that key in the sgct repository code.
Update of config/gui_projector.json to position non-gui window in 2nd monitor (dimensions will need to be customized to fit).
If option "show only user interface on the first window" is checked, then all subsequent windows will have 2D rendering disabled.
> Improve behavior for gui window and separate render window

- modules/base/rendering/renderabletrailtrajectory.cpp
- modules/base/rendering/renderabletrailtrajectory.h
- Implemented iterative approach for calculating all vertex positions in the trail. Instead of doing all calculations at once, which takes time and locks the thread, we instead calculate a smaller portion (chunk) of the vertices each frame. Once all vertices are calculated we commit it for rendering.
- Moved the calculations for the bounding sphere into the "vertex calculation" loop in order to minimize unnecessary looping. Before we also calculated the bounding sphere each frame, but this is now changed to only be done after each full sweep.
- Iterative approach: The program now runs without locking up when first loading large RenderableTrailTrajectories into the scene, albeit at a lower framerate.
- Bounding Sphere: Since bounding sphere calculations are only done when needed. 
Example, …
> Optimization update for RenderableTrailTrajectory

- include/openspace/rendering/renderable.h
- modules/globebrowsing/src/renderableglobe.cpp
- modules/globebrowsing/src/renderableglobe.h
- src/rendering/renderable.cpp
- src/scene/scenegraphnode.cpp
Fixes https://github.com/OpenSpace/OpenSpace/issues/1610 and fixes https://github.com/OpenSpace/OpenSpace/issues/1617 by rendering the globelabels after the atmosphere
Also fixes a problem with opacity not really working for globelabels on celestial bodies with an atmosphere
And allows for rendering the upcoming GeoJson component as part of the renderable globe
> Double renderbins for renderables

- include/openspace/scene/assetmanager.h
- src/scene/assetmanager.cpp
See issue #2513 for the problem of non-deterministic asset add/removal, with an example of a problem caused by it. This change of containers for assets to be added/removed seems to avoid the problem.
This change was run on the linux image test server. Results were positive but with a few possible artifacts due to this change. Needs some additional testing.
> Switch to std::list for adding & removing assets in deterministic order

- apps/OpenSpace/ext/launcher/src/sgctedit/windowcontrol.cpp
Fix for issue #2546. Provides a correct FOV for both portrait or landscape window configuration. Also improves on the previous scaling code which didn't work well for elongated windows.
> Use correct FOV calculations to handle portrait or landscape windows

- data/assets/scene/solarsystem/interstellar/c-2019_q4_borisov.asset
- data/assets/scene/solarsystem/interstellar/oumuamua.asset
- data/assets/scene/solarsystem/sssb/amor_asteroid.asset
- data/assets/scene/solarsystem/sssb/apollo_asteroid.asset
- data/assets/scene/solarsystem/sssb/astraea.asset
- data/assets/scene/solarsystem/sssb/aten_asteroid.asset
- data/assets/scene/solarsystem/sssb/atira_asteroid.asset
- data/assets/scene/solarsystem/sssb/c2019y4atlas.asset
- data/assets/scene/solarsystem/sssb/centaur_asteroid.asset
- data/assets/scene/solarsystem/sssb/chiron-type_comet.asset
- data/assets/scene/solarsystem/sssb/encke-type_comet.asset
- data/assets/scene/solarsystem/sssb/halley-type_comet.asset
- data/assets/scene/solarsystem/sssb/inner_main_belt_asteroid.asset
- data/assets/scene/solarsystem/sssb/itokawa.asset
- data/assets/scene/solarsystem/sssb/jupiter-family_comet.asset
- data/assets/scene/solarsystem/sssb/jupiter_trojan_asteroid.asset
- data/assets/scene/solarsystem/sssb/main_belt_asteroid.asset
- data/assets/scene/solarsystem/sssb/mars-crossing_asteroid.asset
- data/assets/scene/solarsystem/sssb/outer_main_belt_asteroid.asset
- data/assets/scene/solarsystem/sssb/pha.asset
- data/assets/scene/solarsystem/sssb/swifttuttle.asset
- data/assets/scene/solarsystem/sssb/transneptunian_object_asteroid.asset
All assets that use Horizons ephemeris were checked recently for updated positions. For all files where the ephemeris had been updated, the new file was downloaded from JPL and added to the Utah data server with an updated version number.
For testing, it will be necessary to switch the openspace.cfg file's sync entry to:
`HttpSynchronizationRepositories = { "http://openspace.sci.utah.edu/request" }`
since data.openspaceproject.com does not yet have this data.
> Updating assets that use updated Horizons data files

- data/profiles/rosetta.profile
When time is moved to before or after the image acquisition sequence, 67P shading will be turned on so that it looks better. Script scheduler is used so that this works for forward or reverse time shifts.
> Adds scheduled scripts to enable shading outside of image acquisitions

- apps/OpenSpace/ext/launcher/include/profile/cameradialog.h
- apps/OpenSpace/ext/launcher/resources/qss/launcher.qss
- apps/OpenSpace/ext/launcher/src/profile/cameradialog.cpp
- include/openspace/navigation/navigationhandler.h
- include/openspace/navigation/waypoint.h
- include/openspace/scene/profile.h
- modules/base/lightsource/scenegraphlightsource.cpp
- src/engine/openspaceengine.cpp
- src/navigation/navigationhandler.cpp
- src/navigation/navigationstate.cpp
- src/navigation/path.cpp
- src/navigation/waypoint.cpp
- src/scene/profile.cpp
- tests/profile/basic/camera_gotonode.profile
- tests/profile/basic/camera_gotonode_height.profile
- tests/profile/error/camera/gotonode_invalidvalue_negative_height.profile
- tests/profile/error/camera/gotonode_invalidvalue_zero_height.profile
- tests/profile/error/camera/gotonode_missing_anchor.profile
- tests/profile/error/camera/gotonode_wrongtype_anchor.profile
- tests/profile/error/camera/gotonode_wrongtype_height.profile
- tests/test_profile.cpp
Adds a tab for specifying a scene graph node (and makes that the default one)
Also added some descriptive text to each tab. Let me know what you think of them.
Used the already existing camera path waypoint creation code to compute the camera position, but unfortunately, the actual camera pose can't be computed until we reach the "first correct frame", so the code ended up being much uglier than I wanted it to be... (the check in navigationhandler.cpp). But it works, and that's what most important by now :) 
Do we also want to allow the user to set an optional height value? Since this is supported by the data structure used for the camera position, this might make sense
> Issue/2227 - Option to just specify a scene graph node in profile editor camera dialog

- modules/space/rendering/renderableorbitalkepler.cpp
- modules/space/rendering/renderableorbitalkepler.h
Switched multiple OpenGL calls to single a call for better efficiency from `glDrawArrays` to `glMultiDrawArrays` .
This increases performance when rendering Main Asteroid Belt from 20 fps to 85 fps on my machine.
> Switched multiple OpenGL calls to a single call for better efficiency

- apps/OpenSpace/ext/launcher/include/profile/propertiesdialog.h
- apps/OpenSpace/ext/launcher/src/profile/propertiesdialog.cpp
The profile editor's property dialog now has two ways of adding a property: manual or fill-from-scriptlog. This change prevents user from being able to select the scriptlog fill option if the editor is currently in edit mode (adding or changing a property).
> Fix for preventing adding property from scriptlog if already in add mode

- data/assets/scene/solarsystem/sssb/amor_asteroid.asset
- data/assets/scene/solarsystem/sssb/apollo_asteroid.asset
- data/assets/scene/solarsystem/sssb/aten_asteroid.asset
- data/assets/scene/solarsystem/sssb/atira_asteroid.asset
- data/assets/scene/solarsystem/sssb/centaur_asteroid.asset
- data/assets/scene/solarsystem/sssb/chiron-type_comet.asset
- data/assets/scene/solarsystem/sssb/encke-type_comet.asset
- data/assets/scene/solarsystem/sssb/halley-type_comet.asset
- data/assets/scene/solarsystem/sssb/inner_main_belt_asteroid.asset
- data/assets/scene/solarsystem/sssb/jupiter-family_comet.asset
- data/assets/scene/solarsystem/sssb/jupiter_trojan_asteroid.asset
- data/assets/scene/solarsystem/sssb/main_belt_asteroid.asset
- data/assets/scene/solarsystem/sssb/mars-crossing_asteroid.asset
- data/assets/scene/solarsystem/sssb/outer_main_belt_asteroid.asset
- data/assets/scene/solarsystem/sssb/pha.asset
- data/assets/scene/solarsystem/sssb/transneptunian_object_asteroid.asset
- modules/space/kepler.cpp
The JPL SSSB site changed their date format from `YYYYMMDD` to `YYYY-MM-DD`. Our v1 asteroids files have the first date format, and our v2 files have the second.
This version will accept either of these two format, so that the older v1 files will still work.
**Important Note for Testing this PR:**
The crash mentioned in issue 2649 only occurs if OpenSpace was built in Debug mode.
In order to verify this fix, the following are required:
- Build & run OpenSpace in Debug mode
- Delete all cache folders that begin with _sssb_data__
- Delete all folders in sync/http that begin with _sssb_data__
- In openspace.cfg entry for `Sync{HttpSynchronizationRepositories}`, comment-out all other servers except for `http://openspace.sci.utah.edu/request`.
> Fix for date format in sssb v2 asteroids files (issue 2649)

- modules/base/rendering/renderabletrailtrajectory.cpp
____________________________________
**Note**: the end point is added afterwards and is not included in this variable
> Fixes #2540 by correctly showing all points, including the proper end point

- config/portrait_with_gui.json
Adds a new window config with a 9:16 portrait render window. Uses a render-less GUI window to the side in landscape orientation, which is necessary in order to access the full GUI menu.
> Portrait window config for issue#2383

- modules/globebrowsing/src/layer.cpp
- modules/globebrowsing/src/layer.h
- modules/globebrowsing/src/layergroup.cpp
Added a simple check to see if the layer is initialized before calling the update function.
> Don't call update function unless layer has been initialized

- modules/globebrowsing/src/renderableglobe.cpp
This is really this PR: https://github.com/OpenSpace/OpenSpace/pull/2756
But I accidentally closed it when fxing a naming mistake in the branch name... 
The conclusion was that the offset seems to greatly remedy the behavior of the issue https://github.com/OpenSpace/OpenSpace/issues/2696, but it only fixes the symptom, not the underlying cause. Before the height tiles are fully loaded, it is still possible to intersect the planetary surface. 
Only affect the estimation of height values based on the camera position
> Offset sample coordinate by 0.5 when estimating height values

- modules/globebrowsing/shaders/texturetilemapping.glsl
- modules/globebrowsing/shaders/tile.glsl
- modules/globebrowsing/src/gpulayergroup.cpp
- modules/globebrowsing/src/gpulayergroup.h
- modules/globebrowsing/src/layer.cpp
- modules/globebrowsing/src/layer.h
- modules/globebrowsing/src/memoryawaretilecache.cpp
- modules/globebrowsing/src/rawtiledatareader.cpp
- modules/globebrowsing/src/rawtiledatareader.h
- modules/globebrowsing/src/renderableglobe.cpp
- modules/globebrowsing/src/renderableglobe.h
- modules/globebrowsing/src/tileprovider/defaulttileprovider.cpp
- modules/globebrowsing/src/tileprovider/defaulttileprovider.h
- modules/globebrowsing/src/tileprovider/temporaltileprovider.cpp
- modules/globebrowsing/src/tileprovider/tileprovider.cpp
- modules/globebrowsing/src/tiletextureinitdata.cpp
- modules/globebrowsing/src/tiletextureinitdata.h
Solves #2472 #2834 and #2841 
Tiles were previously padded both during read and rendering with 4 pixels on each side (or the corresponding amount of pixels during read). This caused issues both with color & height maps.
For colormaps the default rendering was done without padding but the rasterreads were performed with padding, this caused the entire texture to become squeezed and visually "move" towards the corners as higher-resolution tiles were loaded.
In addition; for heightmaps it caused excessive sampling in-between pixels which enhanced stair-stepping artifacts.
All of the changes in this PR, alongside with potential changes to the underlying VRT dataset as described [in this PR](https://github.com/OpenSpace/openspace.github.io/pull/30) provides significant improvements to …
> Remove tile-padding to reduce stair-stepping issues

- apps/OpenSpace/ext/launcher/include/profile/assetsdialog.h
- apps/OpenSpace/ext/launcher/src/profile/assetsdialog.cpp
It can be hard to find an asset in the profile editor since there are many assets, and the tree view has collapsed branches by default for directories that don't contain any currently-selected assets.
This adds a text box above the tree view to allow for easy searching of the available asset files.
> Add search text box and filtering capability to Launcher profile assets editor

- include/openspace/navigation/orbitalnavigator.h
- src/navigation/orbitalnavigator.cpp
To discuss: Do we need similar settings for other camera motions, like panning and global rotation?  Should I add these too?
We used this setting in the Stort installation, to prevent the user from moving closer to objects in certain scenarios, without having to set exact distances for limiting the vertical navigation
Added warnings that show if either property is disabled. Feels like one of those things the user could easily forget is disabled, and be confused about. The warning increases the visibility of the effect, and warns the user about the consequences
> Add options to disable roll and zoom in OrbitalNavigator

- config/schema/sgcteditor.schema.json
Fixes issue 2860 by correcting typo in sgct schema file, which allows editing of user-created config files again.
> Fix for issue/2860

- include/openspace/rendering/screenspacerenderable.h
- modules/base/rendering/screenspaceframebuffer.cpp
- modules/base/rendering/screenspaceframebuffer.h
- modules/base/shaders/screenspace_fs.glsl
- modules/skybrowser/include/screenspaceskybrowser.h
- modules/skybrowser/src/screenspaceskybrowser.cpp
- modules/video/include/screenspacevideo.h
- modules/video/src/screenspacevideo.cpp
- modules/webbrowser/include/screenspacebrowser.h
- modules/webbrowser/src/screenspacebrowser.cpp
- src/rendering/renderengine.cpp
- src/rendering/screenspacerenderable.cpp
Adds a new property to all ScreenSpaceRenderables `RenderDuringBlackout` that controls whether a ScreenSpaceRenderable should listen to the BlackoutFactor of the RenderEngine or not.  If it does listen, it will darken the image by the same value as the 3D rendering, if it does not listen, it will always render at full brightness.
Also fixed the issue where no ScreenSpaceRenderables are rendered when the blackout factor is 0
> Add a proper blackout to the ScreenSpaceRenderables and a property and codegen option to toggle that behavior

- include/openspace/navigation/orbitalnavigator.h
- src/navigation/orbitalnavigator.cpp
Adds a setting to let the user orbit around a certain axis (referred to as the "up") using the OrbitalNavigator. The axis can be set to either the local X Y or Z of the anchor node. 
Input in the x-direction will rotate around the provided vector, while input in the y-direction will move the camera as regular.  It works best when the "up" vector is set to point upwards in screen-space (we should maybe add a way to enforce this)
Should close https://github.com/OpenSpace/OpenSpace/issues/1372  (and partly https://github.com/OpenSpace/OpenSpace/issues/740?)
Here's a demonstration video of how it works. Feel free to try it out.  
https://github.com/OpenSpace/OpenSpace/assets/8808894/51f0cf30-1088-4f3d-a3ee-148e57796e6b
> Feature - OrbitalNavigator Setting - Orbit Around Up

- include/openspace/rendering/renderable.h
Compilers besides Windows msvc throw an error when encountering an empty initializer list for a struct, even though that struct is fully-specified with default values.
This fix explicity provides the three `std::nullopt` values for the `AlternativeTransform` struct.
> Non-Windows compiler fix for empty initializer list

- include/openspace/util/resourcesynchronization.h
- modules/atmosphere/shaders/atmosphere_deferred_fs.glsl
- modules/sync/syncs/httpsynchronization.cpp
- modules/sync/syncs/httpsynchronization.h
- src/util/resourcesynchronization.cpp
Reads ossync file on synchronization and download files that are missing, will automatically retry download if an error occurred.
> Update HttpSynchronization to keep track of files downloaded (#2587)

- src/navigation/path.cpp
Make it more obvious when the camera path speed is infinite (duration is zero), and prevent doing redundant computations.  Instead, just jump to the end of the path in traversal
Honestly, it's just lucky that the math worked before... The use of infinite speed was a bit nasty
> More explicit handling of zero duration paths

- include/openspace/scene/scenegraphnode.h
- src/scene/scenegraphnode.cpp
Closes #1828 
Have been wanting this for a while, and now when we talked about adding other read-only properties to display information, I thought it could be a good (and simple) approach for this issue
> Add property for actual bounding and interaction sphere value

- include/openspace/navigation/navigationhandler.h
- src/navigation/navigationhandler.cpp
Closes #2949 by not limiting the events being triggered to one per frame (i.e. not assuming a smooth transition between the different spheres)
Also checks if the anchor node has changed since last frame and trigger events accordingly.
> Issue/2949 - Fix for camera transition events

- apps/OpenSpace/ext/launcher/src/launcherwindow.cpp
The launcher calls readMeta in order to get the description to get hover-over tooltip text. If a config file is corrupted (e.g. with a `\` character), then the readMeta function's exception will be caught, and the tooltip will be a "No description available" message.
If user runs with this configuration file, OpenSpace will quit, but with a useful description of why the config file load failed.
> Fix for crash when reading meta of corrupt config file

- include/openspace/events/event.h
- include/openspace/events/eventengine.h
- modules/server/CMakeLists.txt
- modules/server/include/topics/eventtopic.h
- modules/server/src/connection.cpp
- modules/server/src/topics/eventtopic.cpp
- src/engine/openspaceengine.cpp
- src/events/event.cpp
- src/events/eventengine.cpp
Add ability to subscribe to events via js-api. Closes #1810 
example: 
```
const foo = api.startTopic("event", {
event: ["RenderableEnabled", "RenderableDisabled"],
status: "start_subscription"
});
```
where property `event` can be either a string or a list of strings. To subscribe to all events use `"*"` or `"all"`
> Add event topic

- apps/OpenSpace/ext/launcher/src/profile/cameradialog.cpp
- include/openspace/navigation/navigationstate.h
- include/openspace/util/json_helper.h
- src/navigation/navigationhandler.cpp
- src/navigation/navigationhandler_lua.inl
- src/navigation/navigationstate.cpp
Change the navigation state format from Lua to JSON (applies to `openspace.navigation.saveNavigationState` and `openspace.navigation.loadNavigationState`. Before, the `yaw` and `pitch` values were ignored if the `up` vector was not specified. Now, these three values are loaded independently.
Add the ability to set the navigation state in the profile editor based on the new JSON format.
> NavigationState handling

- modules/base/rendering/pointcloud/renderablepointcloud.cpp
- modules/base/rendering/pointcloud/renderablepointcloud.h
- modules/base/shaders/pointcloud/billboardpoint_fs.glsl
Added support for an outline when rendering data as points.
The outline can be enabled/disabled and both thickness and color can be set via GUI and `Assets`.
Additive blending with border
Standard blending with border
Uniform color with border
Uniform color without border
Changed outline color
Changed outline weight (thickness)
> Issue/3043 Added point outlines (RenderablePointCloud)

- data/assets/scene/solarsystem/planets/earth/satellites/misc/iss.asset
- include/openspace/util/spicemanager.h
- modules/space/scripts/spice.lua
- modules/space/spacemodule.cpp
- src/util/spicemanager.cpp
- src/util/spicemanager_lua.inl
Adds two new SPICE functions `openspace.space.convertTLEtoSPK` and `openspace.space.tleToSpiceTranslation`.  The first converts a TLE file into a type 10 SPK kernel t hat can be used for a `SpiceTranslation`.  The second function uses the former to create a kernel and then returns back a fully formed `SpiceTranslation` table that can be used in an asset.
This also hardcoded loads a geophysical constants kernel needed for SPK10 kernels to work.
This PR also applies those changes to the ISS to both fix its position for a longer time (fixes #1578) and use a new dynamic frame kernel to have a correct orientation for the ISS (fixes #1783)
> Add the ability to convert TLE files to SPICE kernels and apply change to ISS

- modules/atmosphere/rendering/atmospheredeferredcaster.cpp
- modules/atmosphere/rendering/atmospheredeferredcaster.h
- modules/atmosphere/rendering/renderableatmosphere.cpp
- modules/atmosphere/rendering/renderableatmosphere.h
- modules/exoplanets/exoplanetsmodule_lua.inl
- modules/globebrowsing/src/renderableglobe.cpp
- modules/globebrowsing/src/renderableglobe.h
Note that for planets with atmospheres, the SunNode has to be specified for _both_ the globe and the atmosphere separately
- Closes #1745
- Closes #2243
> Add the ability to specifiy local Sun position for the RenderableGlobe and RenderableAtmosphere

- src/interaction/sessionrecording.cpp
User can now specify a path with the intended filename when starting a recording. If no path is provided, the file is saved to user/recordings/.
This can be done from either the frontend UI or via `openspace.sessionRecording.startRecording`.
The path must be an _absolute_ path to an existing directory in the filesytem, and the user must have write permissions to it.
The file would have to be played-back using `openspace.sessionRecording.startPlayback`, becuase the UI only lists files that reside in the user/recordings/ directory.
> Allow sessionrecording to write a file outside of user/recordings/

- data/assets/scene/digitaluniverse/stars.asset
- data/assets/scene/milkyway/gaia/apogee.asset
- data/assets/scene/milkyway/gaia/galah.asset
- data/assets/scene/milkyway/objects/orionnebula/cluster.asset
- data/assets/scene/milkyway/stars/denver.asset
- modules/space/rendering/renderablestars.cpp
- modules/space/rendering/renderablestars.h
- modules/space/shaders/star_fs.glsl
- modules/space/shaders/star_ge.glsl
- modules/space/shaders/star_vs.glsl
This changes the RenderableStars to render two textures (a halo + a glare) on top of each other. Each texture component is configurable separately.  This change also has a few quality of life features in the code to remove double negations, etc.
> Updating the star rendering

- modules/base/rendering/pointcloud/renderablepointcloud.cpp
- modules/base/rendering/pointcloud/renderablepointcloud.h
- modules/base/shaders/pointcloud/pointcloud_fs.glsl
Adds border in three different styles and makes it possible to apply color map på border rather than the point body. Closes #3070 
Round, Square, Bottom (with texture and color map to border instead of texture)
And for points without texture (and not using color map, only the previously existing border color)
Notice how the points change from round to square when Square or Bottom border style is chosen
> Issue/3070 - Outline/border to textured points

- modules/atmosphere/rendering/atmospheredeferredcaster.cpp
Fixes a problem where the light source direction was erroneously computed for the atmosphere. It was not noticeable in our solar system but led to errors when adding an atmosphere to an exoplanet system. 
Reported in support slack
https://openspacesupport.slack.com/archives/C04TY4ZKXV2/p1714145171752719
To test it, you can try loading the assets below, that add an exoplanet system with an atmosphere
[kepler36.zip](https://github.com/OpenSpace/OpenSpace/files/15272781/kepler36.zip)
> Fix faulty computation of sun position in atmosphere

- src/engine/syncengine.cpp
closes #3163 and #3257 
The issue is that as we are iterating the syncables in post-synchronization the video player adds a new `syncable` to the `syncEngine` which invalidates the range-based for loop due to vector capacity change. Either we go with this solution of changing it to an index-based for loop (should probably change it in e.g., pre-synchronization as well?) or we add the `syncable` to some queue which we process at the next frame for example.
> Update post synchronization from range-based to index-based for loop closes #3163

- data/assets/global/localbookmarks.asset
- src/scripting/scriptengine.cpp
- src/scripting/scriptengine_lua.inl
There is an option to also create all the directories in the specified path but perhaps that should be its own lua function? 
The `createDirectory` requires that the parent directory exists
closes #3229
> Automatically create bookmarks folder for user 

- src/util/spicemanager.cpp
I got some spice kernels from someone where the extension was .spk 
When I tried to use them, openspace didn't find positions for the object, however when I used brief.exe and spicepy, I did get values. Turns out we only will read positions if the file name ends in .bsp, so I thought since I had to dig into the code to figure this out, maybe we could help any users that this happens to in the future.
> Added extra file extensions for spice kernels

- data/assets/util/joysticks/joystick_helper.asset
- src/navigation/navigationhandler_lua.inl
- src/navigation/pathnavigator_lua.inl
To try to take advantage of new documentation functionalities 
To avoid writing really confusing documentation I have also changed the input parameters of:
* `openspace.navigation.addLocalRoll`
* `openspace.navigation.addGlobalRoll`
* `openspace.navigation.addTruckMovement`
to use 1 parameter instead of 2 (where one was not used in the end)
and tried to fix a gnarly return value for the `openspace.navigation.joystickaxis` function. 
❗ **However, documented structs are not supported as return values in codegen, so this needs some discussion** ❗
> Update Lua script documentation for `openspace.navigation` and `openspace.pathnavigation`

- modules/space/CMakeLists.txt
- modules/space/rendering/renderableorbitalkepler.cpp
- modules/space/rendering/renderableorbitalkepler.h
- modules/space/shaders/debrisVizPoints_fs.glsl
- modules/space/shaders/debrisVizPoints_gs.glsl
- modules/space/shaders/debrisVizPoints_vs.glsl
- modules/space/shaders/debrisVizTrails_fs.glsl
- modules/space/shaders/debrisVizTrails_gs.glsl
Optimization for the trail shader was achieved by using a geometry shader to cull vertices that does not contribute to the final trail. In other words, vertices which part of the trail would be fully faded (discard by fragment shader) is now removed in geometry shader and thus less data is being processed in fragment shader.
Changed nearly all calculations from double to float. Was using double as a safe-guard during development and never revisited that decision. 
Everything is compared to 0.20.0 RC1
The new implementation results in a framerate that does not fluctuate depending on how many pixels the trails cover on screen.
Test using the _Main Asteroid Belt_ at different zoom levels within the solar system
**Before:**
- 60 - 170 fps
- 16.67 - 5.88 ms
**After:**
- 156 fps
- 6.41 ms
At …
> Issue/3286: renderableOrbitalKepler - optimization of point and trail rendering

- data/assets/examples/renderable/renderablesphereimagelocal/sphereimagelocal.asset
- data/assets/examples/renderable/renderablesphereimageonline/sphereimageonline.asset
- modules/base/rendering/renderablesphere.cpp
The example `RenderableSphereImageOnline` was broken due to missing the previously non-optional `Size` parameter. 
Both `Size` and `Segments` have been marked as an advanced user property and should not be mandatory in the asset component specification, so I changed that and added verifiers. 
The example also had a comment about properties from `RenderableSphere`, that the user should ont have to know about. removed this. I also changed the default value to the one we wanted to use for this example, to be a bit smoother per default.
Finally, added a similar example for `RenderableSphereImageLocal`.
> Fix renderable sphere example and add one for using local image

- modules/globebrowsing/globebrowsingmodule_lua.inl
Use new `\param` feature in script function documentation, and make naming and description of script parameters more consistent and correct (identifier VS name, for example)
> Clean up globebrowsing script function documentation and adapt to new format

- src/util/spicemanager_lua.inl
on systems with LF line endings (unix), the parsing would not get rid of the extra CR character causing a parse error for tle files. This PR reads the file in binary mode which is platform independent.
reference: https://en.cppreference.com/w/cpp/io/c/FILE#Binary_and_text_modes
> fix parsing TLE files with CRLF line endings on unix

- modules/sync/syncs/urlsynchronization.cpp
- modules/sync/syncs/urlsynchronization.h
There was an issue with the URL sync when several instances asked Spice for time information at the same time. Since Spice is not multithreaded it could not handle more than 1 request at a time and an exception was thrown occasionally during loading. This did not happen often but can be tested by removing all previous satellite URL sync data from the sync folder and then loading a profile with all satellites. Then all satellites will sync with the URL sync and this crash will most likely happen. This PR fixes this by making the mutex static so all URL sync instances wait their turn before asking Spice for time information. 
I am not sure what we lose by not having the `mutable` keyword for the mutex anymore but from some fast searching, I couldn't find a good way to combine the two …
> Fix url sync 

- modules/volume/CMakeLists.txt
- modules/volume/tasks/generaterawvolumefromfiletask.cpp
- modules/volume/tasks/generaterawvolumefromfiletask.h
- modules/volume/volumemodule.cpp
This PR adds a task to generate a raw volume (used in e.g., RenderableTimeVaryingVolume) from a CSV file. 
Example .task and data file to try it out if you'd like: 
[data.csv](https://github.com/user-attachments/files/16070095/data.csv)
example .task (can't be uploaded) 
return {{
Type = "GenerateRawVolumeFromFileTask",
Dimensions = {16, 16, 16},
Time = "2018-05-04T00:00:00",
DataValue = "value",
DataInputPath = "${USER_ASSETS}/example/data.csv",
RawVolumeOutput = "${USER_ASSETS}/example/volume/exampleVolume.rawvolume",
DictionaryOutput = "${USER_ASSETS}/example/volume/exampleVolume.dictionary"
}}
> Generate raw volume & metadata from csv file - task

- data/assets/scene/digitaluniverse/hdf.asset
The "proximity" parameter does not exist in the dataset. Just add all the parameters to be available for color mapping, but not providing a list at all. Default will be `redshift`, which was in the previous list
I wanted this to go through a PR in case anyone has opinions about removing these preset parameters. The color mapping will likely be slightly different, due the previous custom ranges being slightly different than the automatic one (min and max value of the dataset). 
But this asset is not included in any asset per default and the points are hard to see without changing their scale, so personally I don't think it matters.
> "Fix" warning from hdf.asset

- data/assets/scene/digitaluniverse/grids.asset
- data/assets/util/webgui.asset
- include/openspace/scene/scenegraphnode.h
- src/scene/scenegraphnode.cpp
Adds property the scene graph nodes for sorting the item in the GUI based on a number instead of alphabetically, with respect to its neighboring scene graph nodes in the menu. 
Let me know what you think of the property name `OrderNumber`. Didn't come up with anything better...
This PR should be combined with the following PR in the WebGUI repo: https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/192
Also applies the new sorting to the grids, to sort them based on their size instead of alphabetically:
Note that: 
- Another PR is coming for also controlling the order of the _Groups_ in the UI.
- We do not care about using this ordering in the ImGui UI. Hence why it is not applied there
> Add possiblity to sort SGNs in GUI based on numerical value

- tests/visual/README.md
- tests/visual/renderable/model_vertex_colors.ostest
Note that this PR merges into the branch _feature/model-vertex-colors_, not the _master_ branch. 
Add a new visual test for the RenderableModel with vertex colors. The chosen model is handy as a test since it will show in an obvious way if the vertex colors are not loaded and applied correctly.
Also, I updated the readme file for the visual tests to be easier to read and added the new asset instruction from the PR in the tests repo https://github.com/OpenSpace/OpenSpaceVisualTesting/pull/5.
> Add visual test for vertex colors

- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/definitions/noaa20.asset
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/definitions/noaa21.asset
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/definitions/snpp.asset
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_noaa20_combo.asset
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_snpp_combo.asset
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_viirs_combo.asset
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/viirs_noaa21_temporal.asset
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/viirs_snpp_temporal.asset
- modules/base/rendering/screenspacedashboard.cpp
- modules/globebrowsing/CMakeLists.txt
- modules/globebrowsing/globebrowsingmodule.cpp
- modules/globebrowsing/shaders/texturetilemapping.glsl
- modules/globebrowsing/src/gpulayergroup.cpp
- modules/globebrowsing/src/layer.cpp
- modules/globebrowsing/src/layergroupid.h
- modules/globebrowsing/src/renderableglobe.cpp
- modules/globebrowsing/src/tileprovider/tileproviderbydate.cpp
- modules/globebrowsing/src/tileprovider/tileproviderbydate.h
Adds a new TileProvider (TileProviderByDate) that has a map from date -> TileProvider.  This new tile provider is applied to the VIIIRS instruments on the JPSS satellites (Suomi NPP, NOAA-20, and NOAA-21) to create one asset file that users can use that will automaticalyl select the newest available satellite for the in-game time.  This is a better approach to deal with the multiple layers and effectively closes #3303 as that method would have required an additional internet access where as this will handled locally and will handle the caching transparently as well.
As part of this change the copy-and-pasting of the SNPP, NOAA20, and NOAA21 layer descriptions became pretty high, so this PR also rearranges those layer specifications by creating "definition" files that only _define_ a layer …
> Add new TileProvider to select tile providers based on the date and apply to VIIRS Joint Polar Satellite System

- data/assets/util/webgui.asset
- include/openspace/events/event.h
- include/openspace/properties/numericalproperty.inl
- include/openspace/properties/property.h
- modules/base/rendering/pointcloud/renderableinterpolatedpoints.cpp
- modules/globebrowsing/src/layergroup.cpp
- modules/imgui/src/renderproperties.cpp
- src/documentation/documentationengine.cpp
- src/events/event.cpp
- src/interaction/sessionrecording.cpp
- src/properties/property.cpp
- src/properties/propertyowner.cpp
- src/rendering/renderengine.cpp
- src/scene/profile.cpp
- src/scene/scene.cpp
- src/scene/scene_lua.inl
To be used with this PR: https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/194
This PR will mirror (hopefully) all updates to the property tree in the UI, including:
* All property owner removals and additions during runtime
* All property removals and additions during runtime
* Globebrowsing layer reorderings
Changes made:
* Removed all events for removing and adding SceneGraphNodes, ScreenSpaceRenderables and Layers
* Instead created two new events: PropertyTreeUpdated and PropertyTreePruned
* These events are published in the PropertyOwner functions addProperty, addPropertySubowner, removeProperty, and removePropertySubowner, to ensure that all changes in the property tree are reflected in the UI
* The URI of the Property or PropertyOwner is validated before the event is …
> UI updates

- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback.asset
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20140220.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20150430.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20160613.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20180108.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20180627.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20190626.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20200610.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20210408.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20211221.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20221012.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20230613.wms
- data/assets/scene/solarsystem/planets/earth/layers/colorlayers/esri_world_imagery_wayback/20231207.wms
Add new layers that show the state of the Earth World Imagery at different times (see https://livingatlas.arcgis.com/wayback/ for more information and license information).
> Add Esri Wayback layers

- data/assets/global/localbookmarks.asset
- data/assets/scene/milkyway/constellations/constellation_art.asset
- data/assets/util/constellations_helper.asset
- include/openspace/engine/configuration.h
- include/openspace/scripting/scriptengine.h
- openspace.cfg
- src/engine/configuration.cpp
- src/engine/openspaceengine.cpp
- src/scripting/scriptengine.cpp
This change disables the `require` function in Lua and the `io`, `os`, and `package` tables in an effort to better secure our Lua interpreter against potentially malicious code. There is a new `openspace.cfg` setting `SandboxedLua` that toggles that behavior, with it being _enabled_ by default. 
This change required changing the constellation asset files as they previously relied on the `io` functions. This dependency has been replaced with OpenSpace-native functions instead.
To test in here is whether we have any asset files that no longer work as they require the use of any of the now-removed tables.  If that is the case, the assets need to be rewritten to use (potentially new) OpenSpace functions instead.
> Lua Sandboxing

- modules/exoplanets/exoplanetsmodule_lua.inl
- modules/globebrowsing/src/renderableglobe.cpp
Adds a color to the exoplanets based on their size (Terrestrial, Super-Earth, Neptune-like or Gas giant and larger). 
Other additions include:
- adding a tag `exoplanet_planet` for the exoplanet
- adding descriptions to some of the scene graph nodes that ar eadded as part of the system (partly addresses issue #2864, but not fully)
The colors are inspired by the following graphic from NASA, with constants taken from this source: 
https://www.nasa.gov/image-article/sizes-of-known-exoplanets/
Here's an example for the KOI-351 system, which has planets of all 4 types
> Give exoplanets a color based on their size

- include/openspace/scripting/scriptengine.h
- src/scripting/scriptengine.cpp
- src/scripting/scriptengine_lua.inl
This PR adds two new functions to handle reoccuring scripts:
`openspace.registerRepeatedScript`:  Adds a script to be executed every X seconds wall-clock time. Optionally takes a `preScript` that is run once when registering and a `postScript` that is run once when unregistering.
`openspace.removeRepeatedScript`:  Removes a previously repeated script.
Print the scale of Earth to the console every second
```lua
openspace.registerRepeatedScript("example1", "openspace.printInfo(openspace.propertyValue('Scene.Earth.Scale.Scale'))", 1)
-- ....
openspace.removeRepeatedScript("example1")
```
Every frame set the scale of Mars to be the same as the scale of Earth
```lua
openspace.registerRepeatedScript("example2", "openspace.setPropertyValueSingle('Scene.Mars.Scale.Scale', …
```
> Add ability to schedule Lua scripts

- data/assets/examples/screenspacedistancetoearth.asset
- data/assets/examples/screespacedistancetoearth.asset
Add a screenspace dashboard example for showing the current distance from the camera to Earth, in lightyears.
Also use a custom formatting to not show "camera"
> Screenspace dashboard distance to earth example

- modules/base/dashboard/dashboarditemdistance.cpp
We want to be able to change this property during runtime, from the UI. 
Very small change, but I made this a PR just because I want someone to approve the visibility level change of the properties (changed both the related properties to advanced)
> Do not hide requestedUnit of dashboarditem distance in UI

- include/openspace/engine/openspaceengine.h
- modules/imgui/src/guimemorycomponent.cpp
- src/CMakeLists.txt
- src/engine/openspaceengine.cpp
- src/engine/openspaceengine_lua.inl
- src/rendering/renderengine.cpp
- src/scene/scenegraphnode.cpp
This PR adds two new Lua functions `openspace.ramInUse()` and `openspace.vramInUse()` that report the amount of system memory and video memory used by OpenSpace (in bytes).
This value is also reported in the "Memory Information" ImGUI panel:
And as a plot in Tracy:
> Add the ability to query RAM and VRAM usage

- modules/exoplanets/CMakeLists.txt
- modules/exoplanets/datastructure.cpp
- modules/exoplanets/datastructure.h
- modules/exoplanets/exoplanetshelper.cpp
- modules/exoplanets/exoplanetshelper.h
- modules/exoplanets/exoplanetsmodule.cpp
- modules/exoplanets/exoplanetsmodule_lua.inl
- modules/exoplanets/scripts/systemcreation.lua
- modules/exoplanets/tasks/exoplanetsdatapreparationtask.h
- scripts/core_scripts.lua
So that it can be changed by the user, if desired. Closes #3431 
Please try out the new functions and see if the structure of the new .lua file makes sense, as well as the documentation
Breaking change: `openspace.exoplanet.addExoplanetSystem` no longer have the option of taking a list of star names. INstead, a new function `openspace.exoplanet.addExoplanetSystems` was added to add multiple exoplanet systems in one function call
Note that there are some `TODO` comments still around in the .lua file. These will be addressed by another PR
> Move Exoplanet creation code from C++ to Lua 

- data/assets/examples/renderable/renderablecartesianaxes/cartesianaxes.asset
- data/assets/examples/renderable/renderablecartesianaxes/cartesianaxes_customcolor.asset
- data/assets/examples/renderable/renderablecartesianaxes/cartesianaxes_parent.asset
- modules/base/rendering/renderablecartesianaxes.cpp
- modules/base/shaders/axes_fs.glsl
* Add opacity property and make axes fade like every other renderable
* Small update to existing documentation to utilize Markdown features and links to other classes
* Add examples for specifying a Parent node and using custom colors
> Polish `RenderableCartesianAxes` - documentation, examples, and make fading work correctly

- data/assets/examples/renderable/renderableboxgrid/boxgrid.asset
- data/assets/examples/renderable/renderableboxgrid/boxgrid_size.asset
- data/assets/examples/renderable/renderableboxgrid/boxgrid_styled.asset
- modules/base/rendering/grids/renderableboxgrid.cpp
- modules/base/rendering/grids/renderableboxgrid.h
Adds examples for `RenderableBoxGrid`, as well as a short description for the docs page. 
Edit:  Concluded to remove the Labels component. Below are the notes I added in the PR originally. 
❗ Breaking change:  `RenderableBoxGrid` no longer supports labels 
> _OBS!_ I noticed that the renderable has the option to add a labels component.  However, we don't use this feature anywhere, and when doing a (very small and not at all thorough) attempt to add labels I couldn't get them to show. 
> 
> Do we want to keep the Labels Component feature for `RenderableBoxGrid`? My suggestion would be to remove it for now, since it's not used and adding labels is a bit unintuitive* with the current label code. And then add it again once the labels code has been rewritten (and we add labels to all the grid …
> Docs and examples for `RenderableBoxGrid`

- modules/space/rendering/renderableconstellationbounds.cpp
- modules/space/rendering/renderableconstellationlines.cpp
- modules/space/rendering/renderableconstellationsbase.cpp
Add descriptions of the renderables that are related to constellations. 
No examples added here, as I believe we intend to change how these renderables work slightly in the future and making clear examples didn't feel wort the effort. 
Also note that for the same reason I did not add a description about the file format for the constellation lines, as I believe that we intend to get rid of this format in the future. 
The length of these descriptions say something about the complexity of the abbreviation system and how the `NamesFile` is used. Maybe we should have a separate docs page that explain this, that we can link to from here instead. But now we at least have some description here, in the place where the user would be looking to try to understand how the renderables work.
> Docs for `RenderableConstellationLines` and `RenderableConstellationBounds`

- CMakeLists.txt
- apps/OpenSpace/CMakeLists.txt
- ext/CMakeLists.txt
- don't build the codegen unit tests if the OpenSpace unit tests are disabled
- propagate the value of this option to Ghoul's corresponding option
> cmake: honor OPENSPACE_HAVE_TESTS at more places

- include/openspace/scene/scenegraphnode.h
- src/scene/scenegraphnode.cpp
For use in the new UI implementation?   I don't think we need to make use of this in the current implementation.  The idea being that the "Focus" and "Fly to" and "Frame" buttons wouldn't show up for the scene graph nodes that have this property false.  They'd also not show up in the Focus list
> Add new property hint to determine if a scene graph node should focusable

- modules/base/rendering/grids/renderableboxgrid.cpp
- modules/debugging/scripts/axes.lua
- modules/gaia/scripts/filtering.lua
- modules/globebrowsing/scripts/layer_support.lua
- modules/globebrowsing/scripts/node_support.lua
- modules/globebrowsing/src/globetranslation.cpp
- scripts/core_scripts.lua
- src/navigation/navigationstate.cpp
Just found an old branch from October last year where I had started making some updates to the Lua API functions that are defined in `.lua` files. 
The changes include using the new documentation features like adding parameter descriptions and using Markdown notation. It also formats the descriptions to be more consistent with the other script descriptions (with a dot at the end). 
This PR also:
* Fixes some issues with the gaia module's filtering functions. They were previously broken. 
* Makes it possible to create a `RenderableBoxGrid` that is smaller than 1.
> Utilize new docs functionality in API scripts that are defined in Lua files

- include/openspace/navigation/orbitalnavigator.h
- src/engine/openspaceengine.cpp
- src/navigation/navigationhandler.cpp
- src/navigation/navigationhandler_lua.inl
- src/navigation/orbitalnavigator.cpp
Add a Lua API function for setting the focus node, which includes options to control whether to retarget and/or reset camera velocities
Will be used by the new UI to greatly simplify the code in the navigation panel, and can hopefully be useful in general for our users as well. Maybe in the ShowBuilder, for example?
The code for dealing with the anchor/aim updates has always been confusing, so I also did some minor tidying among the function names to try to reduce that confusion.
> Add Lua function `openspace.navigation.setFocus(identifier, shouldRetarget, shouldResetVelocities)`

- data/assets/examples/dashboarditem/dashboarditemcameraorientation/cameraorientation.asset
- modules/base/CMakeLists.txt
- modules/base/basemodule.cpp
- modules/base/dashboard/dashboarditemcameraorientation.cpp
- modules/base/dashboard/dashboarditemcameraorientation.h
Shows the orientation in Yaw/Pitch/Roll.  Added this as we had screenshots submitted as bugs and trying to recreate it, we have information about the camera location, but not the orientation.
> Add a new DashboardItem to show the camera orientation

- data/assets/examples/rotation/spicerotation/timeoffset.asset
- data/assets/examples/translation/spicetranslation/timeoffset.asset
- modules/space/rotation/spicerotation.cpp
- modules/space/rotation/spicerotation.h
- modules/space/translation/spicetranslation.cpp
- modules/space/translation/spicetranslation.h
Lets SpiceTranslation and SpiceRotation compute the transformation with a given time offset compared to the simulation time (or fixed date if one is configured).
Closes #3531.
> Spice transform: add a "time offset" option

- include/openspace/interaction/action.h
- src/documentation/documentationengine.cpp
- src/interaction/actionmanager_lua.inl
Add the ability to the backend to specify a background color and a text color for actions.  Addresses the backend work for #3538
> Specify background and text colors for actions

- openspace.cfg
- scripts/configuration_helper.lua
- src/engine/configuration.cpp
Use built-in to JSON converter instead of manually creating the string as that had issues with locale-specific number formats (closes #3547). The configuration_helper now uses the nlohmann library exposed through a new Lua function.
While in there, I also removed the ability to create fisheye configuration files from the Lua script directly as we have moved past wanting users to edit the `openspace.cfg` file for these things.
Note:  For this change to work, a change in the serialization of `ghoul::Dictionary`s was necessary.  When serializing a Dictionary, we now check whether we have an array-style dictionary (= only numerical keys that are starting at 1 and are increasing in values without gaps) and if so, serialize it as an array instead.   Prior to this, a Dictionary like:
```cpp …
```
> Window Configuration Generation

- openspace.cfg
It is not by default placed in `user/globebrowsing`
Closes #3512
> Move the OpenSpaceData folder by default into the user folder

- CMakeLists.txt
- modules/webbrowser/CMakeLists.txt
Update submodules and also provide compatibility with CMake 4.0.
- assimp: `v5.4.1` -> `v5.4.3`
- catch: `v3.5.3` -> `3.8.0`
- date: `master` -> `v3.0.3`
- freetype2: `v2.10.4` -> `v2.13.3`. Also change to freetypes original Git server
- glbindings: `v3.3.0` -> `v3.4.0`
- glm: `master` -> `v1.0.2`
- scnlib: `v4.0.1` -> `v2.0.2`
- soloud: `master` -> `master`
- tinyxml: `master` -> `v11.0.0`
- tracy: `v0.10.1` -> `v0.11.0`
> Submodule updates

- data/assets/examples/screenspacerenderable/screenspacerenderablerenderable/renderablerenderable.asset
- data/assets/examples/screenspacerenderable/screenspacerenderablerenderable/renderablerenderable_axes.asset
- data/assets/examples/screenspacerenderable/screenspacerenderablerenderable/renderablerenderable_model-distance.asset
- data/assets/examples/screenspacerenderable/screenspacerenderablerenderable/renderablerenderable_model.asset
- data/screenspacerenderablerenderable.asset
- modules/base/CMakeLists.txt
- modules/base/basemodule.cpp
- modules/base/rendering/screenspacedashboard.cpp
- modules/base/rendering/screenspaceframebuffer.cpp
- modules/base/rendering/screenspaceframebuffer.h
- modules/base/rendering/screenspacerenderablerenderable.cpp
- modules/base/rendering/screenspacerenderablerenderable.h
- src/properties/propertyowner.cpp
- src/scene/scenegraphnode.cpp
New ScreenSpace type that takes a `Renderable` and renders it into a framebuffer displayed in a screenspace renderable window.
While I didn't like the name ScreenSpaceRenderableRenderable in the beginning, I grew on me over the weekend.  Still very much open for better names.
Closes #1720
> Add ScreenSpaceRenderableRenderable class

- src/rendering/colormappingcomponent.cpp
Add documentation for the `ColorMappingComponent` type in "Other", and update some of the descriptions a bit to better match the format on the docs page. 
Note that specifying a file is now required. It didn't really make sense that it was optional, and this simplified the documentation writing.
> Add documentation for `ColorMappingComponent`

- src/properties/misc/optionproperty.cpp
* Fixes hard crash when adding options dynamically with for example color mapping asset (out of bounds crash)
* Removes duplicate notifyChangeListeners (the NumericalProperty::SetValue function already calls notifyChangeListeners)
> Fix out of bounds crash and remove duplicate notifyChangeListeners

- modules/webbrowser/src/eventhandler.cpp
Fixes the issue of not being able to use English keyboard and writing " in CEF. 
To test:
* Write in Swedish and English keyboard to see nothing else broke
* Switch to english keyboard and write ' and " and see that it works now
Closes #2761
> Add handling for apostrophe code

- apps/OpenSpace/main.cpp
- include/openspace/engine/windowdelegate.h
- include/openspace/rendering/renderengine.h
- modules/skybrowser/src/utility.cpp
- src/rendering/renderengine.cpp
Breaking change as we only had a single property to control the field of view before, and it has been replaced by multiple properties. To keep them organized, a new propertowner has been added.
Example:
Before:
`openspace.setPropertyValue("RenderEngine.HorizFieldOfView", 30.0)`
Now:
`openspace.setPropertyValue("RenderEngine.Windowing.Window_0.HorizFieldOfView", 30.0)`
`openspace.setPropertyValue("RenderEngine.Windowing.Window_1.HorizFieldOfView", 60.0)`
Closes #3555 
Closes #2395
> Add ability to configure horizontal field of view per window instead

- apps/OpenSpace/ext/launcher/CMakeLists.txt
- apps/OpenSpace/ext/launcher/include/notificationwindow.h
- apps/OpenSpace/ext/launcher/resources/qss/launcher.qss
- apps/OpenSpace/ext/launcher/src/launcherwindow.cpp
- apps/OpenSpace/ext/launcher/src/notificationwindow.cpp
- apps/OpenSpace/main.cpp
- include/openspace/engine/settings.h
- src/engine/settings.cpp
This PR adds a new window to the bottom of the Launcher that shows notifications.  The contents of the notifications are sources from this GitHub Repository: https://github.com/OpenSpace/Notifications. The README in the there also explains how to write notifications. It is possible to provide different notifications based on specific OpenSpace versions.
The notification window only shows notifications that are younger than 6 months and any notification that has already been there before the last time OpenSpace started are deemphasized.
For now, notifications are shown even for the `master` branch. Question: Should it?
Closes #773
> Add Notification window to the Launcher

- apps/OpenSpace/ext/launcher/CMakeLists.txt
- apps/OpenSpace/ext/launcher/include/usericon.h
- apps/OpenSpace/ext/launcher/src/splitcombobox.cpp
- apps/OpenSpace/ext/launcher/src/usericon.cpp
Add icon to all user-generated profile and configurations.  The icon is a U for "user generated content" within a circle of one of the logo's primary colors.
Open for comments on the look of the logo.  We can control the size, aspect ratio, and basically draw whatever we'd like, but the limitation is that it has to be on the left side of the text.
Another option would have been to use `setLabelDrawingMode` of the QComboBox, but that was only introduced in the latest Qt version 6.9 and still has some bugs with it.  It would be be possible to customize the rendering of the text with it, that that were to work.
Closes #3576
> Launcher should indicate whether a profile is a standard profile or a user profile 

- apps/OpenSpace/main.cpp
- data/tasks/convertmodel.task
- include/openspace/engine/openspaceengine.h
- modules/base/CMakeLists.txt
- modules/base/basemodule.cpp
- modules/base/task/convertmodeltask.cpp
- modules/base/task/convertmodeltask.h
Adds the ability to pass a tast file via `--task` to the OpenSpace.exe to execute a task at startup.  The task will have access to an OpenGL context and once the tasks provided in the file are finished, the OpenSpace application will automatically close.
As an example of a task, this PR also adds a new model converion task that converts a 3D model format from something AssImp can load into our own cached format.
Add ability to use FileVerifier and DirectoryVerifier on files that don't exist. Updates codegen repository for this, too
Closes #1619
> Add the ability to run as task file at startup

- data/assets/util/webgui.asset
- data/profiles/asteroids.profile
- data/profiles/default.profile
- data/profiles/eclipse.profile
- data/profiles/missions/apollo.profile
- data/profiles/missions/artemis.profile
- data/profiles/missions/bepicolombo.profile
- data/profiles/missions/dawn.profile
- data/profiles/missions/gaia.profile
- data/profiles/missions/juice.profile
- data/profiles/missions/juno.profile
- data/profiles/missions/jwst.profile
- data/profiles/missions/mars.profile
- data/profiles/missions/messenger.profile
- data/profiles/missions/newhorizons.profile
- data/profiles/missions/osirisrex.profile
- data/profiles/missions/rosetta.profile
- data/profiles/missions/voyager.profile
- data/profiles/spaceweather/bastilleday2000.profile
- data/profiles/spaceweather/solarstorm2012.profile
- modules/server/src/topics/profiletopic.cpp
Move the profile name away from the top bar, to be less visually intrusive, and add some more information about the profile, such as the description, file path, author, and license. 
I skipped showing the version in the UI as of now, thinking that this might be more confusing than useful. I also updated the profile description so they all end with punctuation, as it looked weird when they didn't. 
Uses this UI PR: OpenSpace/OpenSpace-WebGui#133
This is what it looks like:
> Move profile name from top bar center to File menu 

- modules/webbrowser/src/cefhost.cpp
According to https://github.com/chromiumembedded/cef/issues/3685, using the so-called "Alloy bootstrap" (which seems to be the default) is deprecated. This causes a warning when starting OpenSpace.
In some setups (e.g. an AppImage build on Ubuntu 22.04), the warning is followed by a fatal error and a crash:
[0505/213642.653624:FATAL:path_service.cc(265)] Failed to get the path for 1001
Following the migration instructions from the aforementioned ticket solve both the warning and the crash.
> webbrowser: Fix CEF deprecation notice and crash

- modules/server/CMakeLists.txt
- modules/server/include/logging/notificationlog.h
- modules/server/include/topics/errorlogtopic.h
- modules/server/src/logging/notificationlog.cpp
- modules/server/src/topics/errorlogtopic.cpp
To make it easier on the frontend / receiving end of the topic to handle the log messages, this update changes the format to a JSON object instead of a fixed string that has to be parsed. 
Need an extra look at how the code is structured/indented. 7 months of frontend automation has ruined my feel for how we indent function params, etc
> `errorlogtopic` send log messages as json object instead of a fixed string

- data/assets/examples/renderable/renderablepointcloud/pointcloud_textured_facecameraposition.asset
- data/assets/scene/digitaluniverse/deepsky.asset
- data/assets/scene/digitaluniverse/milkyway.asset
- data/assets/scene/digitaluniverse/milkyway_arm_labels.asset
- data/assets/scene/digitaluniverse/tully.asset
- modules/base/rendering/pointcloud/renderablepointcloud.cpp
- modules/base/rendering/renderableplane.cpp
- modules/base/rendering/renderableplane.h
- modules/skybrowser/src/renderableskytarget.cpp
A bit of an experimental solution for closing #3554.
Setting the billboarding setting for RenderablePointClouds and RenderablePlane were different:
RenderablePointClouds:
`OrientationRenderOption = "Camera View Direction"`, `OrientationRenderOption = "Camera Position Normal"`, or `OrientationRenderOption = "Fixed Orientation"`
with a default value of "Fixed Orientation" if nothing is specified
RenderablePlane:
`Billboard = true`, or `Billboard = false`.  If `true`, it behaves the same as `"Camera Position Normal"` from the RenderablePointClouds.  The default value is `true` is nothing is specified
RenderablePointClouds and RenderablePlane behave more similar
`Billboard = "Camera View Direction"`, `Billboard = "Camera Position Normal"`, `Billboard = "Fixed Orientation"`, `Billboard = …
> Harmonizing `OrientationRenderOption` and `Billboard` settings.  Make RenderablePlanes use the new setting

- apps/OpenSpace/main.cpp
Some of the mouse cursors referenced in main.cpp ( sgctDelegate.setMouseCursor ) are optional and might not be available. This produces error message "X11: Standard cursor shape unavailable" and subsequently crashes the application. 
See [https://github.com/glfw/glfw/blob/aa5e31356178de43d42f43f48914a62c25033f4b/docs/compat.dox#L88](https://github.com/glfw/glfw/blob/aa5e31356178de43d42f43f48914a62c25033f4b/docs/compat.dox#L88)
Output:
```bash
(D) PathNavigator        The scene graph node 'Root' has no, or a very small, bounding sphere. Using minimal value of 10. This might lead to unexpected results
(D) PathNavigator        The scene graph node 'Root' has no, or a very small, bounding sphere. Using minimal value of 10. This might lead to unexpected results
(D) PathNavigator …
```
> Some X11 cursors in GLFW are optional and result in a crash (GLFW)

- data/assets/examples/geojson/geojson_points-relative.asset
- data/assets/examples/geojson/geojson_points_relative_texture_path.asset
- modules/globebrowsing/globebrowsingmodule.cpp
- modules/globebrowsing/globebrowsingmodule.h
- modules/globebrowsing/src/geojson/geojsoncomponent.cpp
- modules/globebrowsing/src/geojson/geojsonproperties.cpp
- modules/globebrowsing/src/geojson/geojsonproperties.h
- modules/globebrowsing/src/geojson/globegeometryfeature.cpp
- src/rendering/texturecomponent.cpp
Set the current working directory temporarily to the folder where thegeojson is located and convert image path via absPath immediately. Add new test for the relative path.
Closes #3139
> Support relative paths in GeoJSON SpriteTexture

- include/openspace/navigation/navigationhandler.h
- include/openspace/rendering/helper.h
- src/engine/openspaceengine.cpp
- src/navigation/navigationhandler.cpp
- src/rendering/helper.cpp
Adds a new BoolProperty to the NavigationHandler that, if enabled, shows the interaction of the mouse while pressing any button.
(in the image, the OS mouse cursor is at the end of the white line, but is not captured in the screenshot)
Closes #1399
> Add rendering for mouse interaction

- modules/globebrowsing/src/rawtiledatareader.cpp
Addresses the disappearing height level when close to the surface.   The reason seems to be that extra piece of code (now removed) that did some magic and added 3 to the max level of the heightlayer max level, causing invalid tiles to be loaded that were nulled out due to the next NoDataValue.
I couldn't see any other side effects and the color layers max level seems unaffected as well.
Closes #3771
> Remove offset for max chunk level
